package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AllowanceAndDeduction generated by hbm2java
 */
@Entity
@Table(name = "allowance_and_deduction", catalog = "db_payroll", uniqueConstraints = @UniqueConstraint(columnNames = {
		"EmpId", "Month", "Year" }))
public class AllowanceAndDeduction implements java.io.Serializable {

	private Long adid;
	private Long empId;
	private String month;
	private String year;
	private Double alHra;
	private Double alperformance;
	private Double alLta;
	private Double alMedical;
	private Double alConveyance;
	private Double alWashing;
	private Double alFda;
	private Double alEducation;
	private Double alBonus;
	private Double alAdhoc;
	private Double alArreasal;
	private Double alOther;
	private Double dePfrate;
	private Double dePfvalue;
	private Double deEsirate;
	private Double deEsivalue;
	private Double deItrate;
	private Double deItvalue;
	private Double deSalAdvValue;
	private Double deProfTax;
	private Double deFestAdv;
	private Double deCellPhone;
	private Double deLwf;
	private Double deOther;
	private Double basicSalary;
	private Double grossSalary;
	private Double netSalary;
	private Integer plantId;
	private Integer insertedBy;
	private Date insertTs;
	private Integer updatedBy;
	private Date updateTs;

	public AllowanceAndDeduction() {
	}

	public AllowanceAndDeduction(Long empId, String month, String year,
			Double alHra, Double alperformance, Double alLta, Double alMedical,
			Double alConveyance, Double alWashing, Double alFda,
			Double alEducation, Double alBonus, Double alAdhoc,
			Double alArreasal, Double alOther, Double dePfrate,
			Double dePfvalue, Double deEsirate, Double deEsivalue,
			Double deItrate, Double deItvalue, Double deSalAdvValue,
			Double deProfTax, Double deFestAdv, Double deCellPhone,
			Double deLwf, Double deOther, Double basicSalary,
			Double grossSalary, Double netSalary, Integer plantId,
			Integer insertedBy, Date insertTs, Integer updatedBy, Date updateTs) {
		this.empId = empId;
		this.month = month;
		this.year = year;
		this.alHra = alHra;
		this.alperformance = alperformance;
		this.alLta = alLta;
		this.alMedical = alMedical;
		this.alConveyance = alConveyance;
		this.alWashing = alWashing;
		this.alFda = alFda;
		this.alEducation = alEducation;
		this.alBonus = alBonus;
		this.alAdhoc = alAdhoc;
		this.alArreasal = alArreasal;
		this.alOther = alOther;
		this.dePfrate = dePfrate;
		this.dePfvalue = dePfvalue;
		this.deEsirate = deEsirate;
		this.deEsivalue = deEsivalue;
		this.deItrate = deItrate;
		this.deItvalue = deItvalue;
		this.deSalAdvValue = deSalAdvValue;
		this.deProfTax = deProfTax;
		this.deFestAdv = deFestAdv;
		this.deCellPhone = deCellPhone;
		this.deLwf = deLwf;
		this.deOther = deOther;
		this.basicSalary = basicSalary;
		this.grossSalary = grossSalary;
		this.netSalary = netSalary;
		this.plantId = plantId;
		this.insertedBy = insertedBy;
		this.insertTs = insertTs;
		this.updatedBy = updatedBy;
		this.updateTs = updateTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ADId", unique = true, nullable = false)
	public Long getAdid() {
		return this.adid;
	}

	public void setAdid(Long adid) {
		this.adid = adid;
	}

	@Column(name = "EmpId")
	public Long getEmpId() {
		return this.empId;
	}

	public void setEmpId(Long empId) {
		this.empId = empId;
	}

	@Column(name = "Month", length = 45)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "Year", length = 45)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "AlHRA", precision = 9)
	public Double getAlHra() {
		return this.alHra;
	}

	public void setAlHra(Double alHra) {
		this.alHra = alHra;
	}

	@Column(name = "ALPerformance", precision = 9)
	public Double getAlperformance() {
		return this.alperformance;
	}

	public void setAlperformance(Double alperformance) {
		this.alperformance = alperformance;
	}

	@Column(name = "AlLTA", precision = 9)
	public Double getAlLta() {
		return this.alLta;
	}

	public void setAlLta(Double alLta) {
		this.alLta = alLta;
	}

	@Column(name = "AlMedical", precision = 9)
	public Double getAlMedical() {
		return this.alMedical;
	}

	public void setAlMedical(Double alMedical) {
		this.alMedical = alMedical;
	}

	@Column(name = "AlConveyance", precision = 9)
	public Double getAlConveyance() {
		return this.alConveyance;
	}

	public void setAlConveyance(Double alConveyance) {
		this.alConveyance = alConveyance;
	}

	@Column(name = "AlWashing", precision = 9)
	public Double getAlWashing() {
		return this.alWashing;
	}

	public void setAlWashing(Double alWashing) {
		this.alWashing = alWashing;
	}

	@Column(name = "AlFDA", precision = 9)
	public Double getAlFda() {
		return this.alFda;
	}

	public void setAlFda(Double alFda) {
		this.alFda = alFda;
	}

	@Column(name = "AlEducation", precision = 9)
	public Double getAlEducation() {
		return this.alEducation;
	}

	public void setAlEducation(Double alEducation) {
		this.alEducation = alEducation;
	}

	@Column(name = "AlBonus", precision = 9)
	public Double getAlBonus() {
		return this.alBonus;
	}

	public void setAlBonus(Double alBonus) {
		this.alBonus = alBonus;
	}

	@Column(name = "AlAdhoc", precision = 9)
	public Double getAlAdhoc() {
		return this.alAdhoc;
	}

	public void setAlAdhoc(Double alAdhoc) {
		this.alAdhoc = alAdhoc;
	}

	@Column(name = "AlArreasal", precision = 9)
	public Double getAlArreasal() {
		return this.alArreasal;
	}

	public void setAlArreasal(Double alArreasal) {
		this.alArreasal = alArreasal;
	}

	@Column(name = "AlOther", precision = 9)
	public Double getAlOther() {
		return this.alOther;
	}

	public void setAlOther(Double alOther) {
		this.alOther = alOther;
	}

	@Column(name = "DePFRate", precision = 9)
	public Double getDePfrate() {
		return this.dePfrate;
	}

	public void setDePfrate(Double dePfrate) {
		this.dePfrate = dePfrate;
	}

	@Column(name = "DePFValue", precision = 9)
	public Double getDePfvalue() {
		return this.dePfvalue;
	}

	public void setDePfvalue(Double dePfvalue) {
		this.dePfvalue = dePfvalue;
	}

	@Column(name = "DeESIRate", precision = 9)
	public Double getDeEsirate() {
		return this.deEsirate;
	}

	public void setDeEsirate(Double deEsirate) {
		this.deEsirate = deEsirate;
	}

	@Column(name = "DeESIValue", precision = 9)
	public Double getDeEsivalue() {
		return this.deEsivalue;
	}

	public void setDeEsivalue(Double deEsivalue) {
		this.deEsivalue = deEsivalue;
	}

	@Column(name = "DeITRate", precision = 9)
	public Double getDeItrate() {
		return this.deItrate;
	}

	public void setDeItrate(Double deItrate) {
		this.deItrate = deItrate;
	}

	@Column(name = "DeITValue", precision = 9)
	public Double getDeItvalue() {
		return this.deItvalue;
	}

	public void setDeItvalue(Double deItvalue) {
		this.deItvalue = deItvalue;
	}

	@Column(name = "DeSalAdvValue", precision = 9)
	public Double getDeSalAdvValue() {
		return this.deSalAdvValue;
	}

	public void setDeSalAdvValue(Double deSalAdvValue) {
		this.deSalAdvValue = deSalAdvValue;
	}

	@Column(name = "DeProfTax", precision = 9)
	public Double getDeProfTax() {
		return this.deProfTax;
	}

	public void setDeProfTax(Double deProfTax) {
		this.deProfTax = deProfTax;
	}

	@Column(name = "DeFestAdv", precision = 9)
	public Double getDeFestAdv() {
		return this.deFestAdv;
	}

	public void setDeFestAdv(Double deFestAdv) {
		this.deFestAdv = deFestAdv;
	}

	@Column(name = "DeCellPhone", precision = 9)
	public Double getDeCellPhone() {
		return this.deCellPhone;
	}

	public void setDeCellPhone(Double deCellPhone) {
		this.deCellPhone = deCellPhone;
	}

	@Column(name = "DeLWF", precision = 9)
	public Double getDeLwf() {
		return this.deLwf;
	}

	public void setDeLwf(Double deLwf) {
		this.deLwf = deLwf;
	}

	@Column(name = "DeOther", precision = 9)
	public Double getDeOther() {
		return this.deOther;
	}

	public void setDeOther(Double deOther) {
		this.deOther = deOther;
	}

	@Column(name = "BasicSalary", precision = 9)
	public Double getBasicSalary() {
		return this.basicSalary;
	}

	public void setBasicSalary(Double basicSalary) {
		this.basicSalary = basicSalary;
	}

	@Column(name = "GrossSalary", precision = 9)
	public Double getGrossSalary() {
		return this.grossSalary;
	}

	public void setGrossSalary(Double grossSalary) {
		this.grossSalary = grossSalary;
	}

	@Column(name = "NetSalary", precision = 9)
	public Double getNetSalary() {
		return this.netSalary;
	}

	public void setNetSalary(Double netSalary) {
		this.netSalary = netSalary;
	}

	@Column(name = "PlantId")
	public Integer getPlantId() {
		return this.plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
	}

	@Column(name = "InsertedBy")
	public Integer getInsertedBy() {
		return this.insertedBy;
	}

	public void setInsertedBy(Integer insertedBy) {
		this.insertedBy = insertedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsertTs", length = 19)
	public Date getInsertTs() {
		return this.insertTs;
	}

	public void setInsertTs(Date insertTs) {
		this.insertTs = insertTs;
	}

	@Column(name = "UpdatedBy")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdateTs", length = 19)
	public Date getUpdateTs() {
		return this.updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

}
