package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * AttendanceMaster generated by hbm2java
 */
@Entity
@Table(name = "attendance_master", catalog = "db_payroll", uniqueConstraints = @UniqueConstraint(columnNames = {
		"EmpId", "Month", "Year" }))
public class AttendanceMaster implements java.io.Serializable {

	private Long atId;
	private Date timeStamp;
	private Integer empId;
	private String empName;
	private String month;
	private String year;
	private String d1;
	private String d2;
	private String d3;
	private String d4;
	private String d5;
	private String d6;
	private String d7;
	private String d8;
	private String d9;
	private String d10;
	private String d11;
	private String d12;
	private String d13;
	private String d14;
	private String d15;
	private String d16;
	private String d17;
	private String d18;
	private String d19;
	private String d20;
	private String d21;
	private String d22;
	private String d23;
	private String d24;
	private String d25;
	private String d26;
	private String d27;
	private String d28;
	private String d29;
	private String d30;
	private String d31;
	private String monthDays;
	private Double presentDays;
	private Integer weekOff;
	private Double paidLeaves;
	private Double unPaidLeaves;
	private Double absentDays;
	private Double paidHolidays;
	private String paidHalfDays;
	private Double privilageLeavePaid;
	private Double sickLeavePaid;
	private Double casualLeavePaid;
	private Double coffleavePaid;
	private Double privilageLeaveUnPaid;
	private Double sickLeaveUnPaid;
	private Double casualLeaveUnPaid;
	private Double coffleaveUnPaid;
	private Double unPaidHalfLeaves;
	private Double payableDays;
	private Double lwp;

	public AttendanceMaster() {
	}

	public AttendanceMaster(Integer empId, String empName, String month,
			String year, String d1, String d2, String d3, String d4, String d5,
			String d6, String d7, String d8, String d9, String d10, String d11,
			String d12, String d13, String d14, String d15, String d16,
			String d17, String d18, String d19, String d20, String d21,
			String d22, String d23, String d24, String d25, String d26,
			String d27, String d28, String d29, String d30, String d31,
			String monthDays, Double presentDays, Integer weekOff,
			Double paidLeaves, Double unPaidLeaves, Double absentDays,
			Double paidHolidays, String paidHalfDays,
			Double privilageLeavePaid, Double sickLeavePaid,
			Double casualLeavePaid, Double coffleavePaid,
			Double privilageLeaveUnPaid, Double sickLeaveUnPaid,
			Double casualLeaveUnPaid, Double coffleaveUnPaid,
			Double unPaidHalfLeaves, Double payableDays, Double lwp) {
		this.empId = empId;
		this.empName = empName;
		this.month = month;
		this.year = year;
		this.d1 = d1;
		this.d2 = d2;
		this.d3 = d3;
		this.d4 = d4;
		this.d5 = d5;
		this.d6 = d6;
		this.d7 = d7;
		this.d8 = d8;
		this.d9 = d9;
		this.d10 = d10;
		this.d11 = d11;
		this.d12 = d12;
		this.d13 = d13;
		this.d14 = d14;
		this.d15 = d15;
		this.d16 = d16;
		this.d17 = d17;
		this.d18 = d18;
		this.d19 = d19;
		this.d20 = d20;
		this.d21 = d21;
		this.d22 = d22;
		this.d23 = d23;
		this.d24 = d24;
		this.d25 = d25;
		this.d26 = d26;
		this.d27 = d27;
		this.d28 = d28;
		this.d29 = d29;
		this.d30 = d30;
		this.d31 = d31;
		this.monthDays = monthDays;
		this.presentDays = presentDays;
		this.weekOff = weekOff;
		this.paidLeaves = paidLeaves;
		this.unPaidLeaves = unPaidLeaves;
		this.absentDays = absentDays;
		this.paidHolidays = paidHolidays;
		this.paidHalfDays = paidHalfDays;
		this.privilageLeavePaid = privilageLeavePaid;
		this.sickLeavePaid = sickLeavePaid;
		this.casualLeavePaid = casualLeavePaid;
		this.coffleavePaid = coffleavePaid;
		this.privilageLeaveUnPaid = privilageLeaveUnPaid;
		this.sickLeaveUnPaid = sickLeaveUnPaid;
		this.casualLeaveUnPaid = casualLeaveUnPaid;
		this.coffleaveUnPaid = coffleaveUnPaid;
		this.unPaidHalfLeaves = unPaidHalfLeaves;
		this.payableDays = payableDays;
		this.lwp = lwp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AtId", unique = true, nullable = false)
	public Long getAtId() {
		return this.atId;
	}

	public void setAtId(Long atId) {
		this.atId = atId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "EmpId")
	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	@Column(name = "EmpName", length = 45)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "Month", length = 45)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "Year", length = 45)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "D1", length = 6)
	public String getD1() {
		return this.d1;
	}

	public void setD1(String d1) {
		this.d1 = d1;
	}

	@Column(name = "D2", length = 6)
	public String getD2() {
		return this.d2;
	}

	public void setD2(String d2) {
		this.d2 = d2;
	}

	@Column(name = "D3", length = 6)
	public String getD3() {
		return this.d3;
	}

	public void setD3(String d3) {
		this.d3 = d3;
	}

	@Column(name = "D4", length = 6)
	public String getD4() {
		return this.d4;
	}

	public void setD4(String d4) {
		this.d4 = d4;
	}

	@Column(name = "D5", length = 6)
	public String getD5() {
		return this.d5;
	}

	public void setD5(String d5) {
		this.d5 = d5;
	}

	@Column(name = "D6", length = 6)
	public String getD6() {
		return this.d6;
	}

	public void setD6(String d6) {
		this.d6 = d6;
	}

	@Column(name = "D7", length = 6)
	public String getD7() {
		return this.d7;
	}

	public void setD7(String d7) {
		this.d7 = d7;
	}

	@Column(name = "D8", length = 6)
	public String getD8() {
		return this.d8;
	}

	public void setD8(String d8) {
		this.d8 = d8;
	}

	@Column(name = "D9", length = 6)
	public String getD9() {
		return this.d9;
	}

	public void setD9(String d9) {
		this.d9 = d9;
	}

	@Column(name = "D10", length = 6)
	public String getD10() {
		return this.d10;
	}

	public void setD10(String d10) {
		this.d10 = d10;
	}

	@Column(name = "D11", length = 6)
	public String getD11() {
		return this.d11;
	}

	public void setD11(String d11) {
		this.d11 = d11;
	}

	@Column(name = "D12", length = 6)
	public String getD12() {
		return this.d12;
	}

	public void setD12(String d12) {
		this.d12 = d12;
	}

	@Column(name = "D13", length = 6)
	public String getD13() {
		return this.d13;
	}

	public void setD13(String d13) {
		this.d13 = d13;
	}

	@Column(name = "D14", length = 6)
	public String getD14() {
		return this.d14;
	}

	public void setD14(String d14) {
		this.d14 = d14;
	}

	@Column(name = "D15", length = 6)
	public String getD15() {
		return this.d15;
	}

	public void setD15(String d15) {
		this.d15 = d15;
	}

	@Column(name = "D16", length = 6)
	public String getD16() {
		return this.d16;
	}

	public void setD16(String d16) {
		this.d16 = d16;
	}

	@Column(name = "D17", length = 6)
	public String getD17() {
		return this.d17;
	}

	public void setD17(String d17) {
		this.d17 = d17;
	}

	@Column(name = "D18", length = 6)
	public String getD18() {
		return this.d18;
	}

	public void setD18(String d18) {
		this.d18 = d18;
	}

	@Column(name = "D19", length = 6)
	public String getD19() {
		return this.d19;
	}

	public void setD19(String d19) {
		this.d19 = d19;
	}

	@Column(name = "D20", length = 6)
	public String getD20() {
		return this.d20;
	}

	public void setD20(String d20) {
		this.d20 = d20;
	}

	@Column(name = "D21", length = 6)
	public String getD21() {
		return this.d21;
	}

	public void setD21(String d21) {
		this.d21 = d21;
	}

	@Column(name = "D22", length = 6)
	public String getD22() {
		return this.d22;
	}

	public void setD22(String d22) {
		this.d22 = d22;
	}

	@Column(name = "D23", length = 6)
	public String getD23() {
		return this.d23;
	}

	public void setD23(String d23) {
		this.d23 = d23;
	}

	@Column(name = "D24", length = 6)
	public String getD24() {
		return this.d24;
	}

	public void setD24(String d24) {
		this.d24 = d24;
	}

	@Column(name = "D25", length = 6)
	public String getD25() {
		return this.d25;
	}

	public void setD25(String d25) {
		this.d25 = d25;
	}

	@Column(name = "D26", length = 6)
	public String getD26() {
		return this.d26;
	}

	public void setD26(String d26) {
		this.d26 = d26;
	}

	@Column(name = "D27", length = 6)
	public String getD27() {
		return this.d27;
	}

	public void setD27(String d27) {
		this.d27 = d27;
	}

	@Column(name = "D28", length = 6)
	public String getD28() {
		return this.d28;
	}

	public void setD28(String d28) {
		this.d28 = d28;
	}

	@Column(name = "D29", length = 6)
	public String getD29() {
		return this.d29;
	}

	public void setD29(String d29) {
		this.d29 = d29;
	}

	@Column(name = "D30", length = 6)
	public String getD30() {
		return this.d30;
	}

	public void setD30(String d30) {
		this.d30 = d30;
	}

	@Column(name = "D31", length = 6)
	public String getD31() {
		return this.d31;
	}

	public void setD31(String d31) {
		this.d31 = d31;
	}

	@Column(name = "MonthDays", length = 45)
	public String getMonthDays() {
		return this.monthDays;
	}

	public void setMonthDays(String monthDays) {
		this.monthDays = monthDays;
	}

	@Column(name = "PresentDays", precision = 9)
	public Double getPresentDays() {
		return this.presentDays;
	}

	public void setPresentDays(Double presentDays) {
		this.presentDays = presentDays;
	}

	@Column(name = "WeekOff")
	public Integer getWeekOff() {
		return this.weekOff;
	}

	public void setWeekOff(Integer weekOff) {
		this.weekOff = weekOff;
	}

	@Column(name = "PaidLeaves", precision = 9)
	public Double getPaidLeaves() {
		return this.paidLeaves;
	}

	public void setPaidLeaves(Double paidLeaves) {
		this.paidLeaves = paidLeaves;
	}

	@Column(name = "UnPaidLeaves", precision = 9)
	public Double getUnPaidLeaves() {
		return this.unPaidLeaves;
	}

	public void setUnPaidLeaves(Double unPaidLeaves) {
		this.unPaidLeaves = unPaidLeaves;
	}

	@Column(name = "AbsentDays", precision = 9)
	public Double getAbsentDays() {
		return this.absentDays;
	}

	public void setAbsentDays(Double absentDays) {
		this.absentDays = absentDays;
	}

	@Column(name = "PaidHolidays", precision = 9)
	public Double getPaidHolidays() {
		return this.paidHolidays;
	}

	public void setPaidHolidays(Double paidHolidays) {
		this.paidHolidays = paidHolidays;
	}

	@Column(name = "PaidHalfDays", length = 45)
	public String getPaidHalfDays() {
		return this.paidHalfDays;
	}

	public void setPaidHalfDays(String paidHalfDays) {
		this.paidHalfDays = paidHalfDays;
	}

	@Column(name = "PrivilageLeavePaid", precision = 9)
	public Double getPrivilageLeavePaid() {
		return this.privilageLeavePaid;
	}

	public void setPrivilageLeavePaid(Double privilageLeavePaid) {
		this.privilageLeavePaid = privilageLeavePaid;
	}

	@Column(name = "SickLeavePaid", precision = 9)
	public Double getSickLeavePaid() {
		return this.sickLeavePaid;
	}

	public void setSickLeavePaid(Double sickLeavePaid) {
		this.sickLeavePaid = sickLeavePaid;
	}

	@Column(name = "CasualLeavePaid", precision = 9)
	public Double getCasualLeavePaid() {
		return this.casualLeavePaid;
	}

	public void setCasualLeavePaid(Double casualLeavePaid) {
		this.casualLeavePaid = casualLeavePaid;
	}

	@Column(name = "COFFLeavePaid", precision = 9)
	public Double getCoffleavePaid() {
		return this.coffleavePaid;
	}

	public void setCoffleavePaid(Double coffleavePaid) {
		this.coffleavePaid = coffleavePaid;
	}

	@Column(name = "PrivilageLeaveUnPaid", precision = 9)
	public Double getPrivilageLeaveUnPaid() {
		return this.privilageLeaveUnPaid;
	}

	public void setPrivilageLeaveUnPaid(Double privilageLeaveUnPaid) {
		this.privilageLeaveUnPaid = privilageLeaveUnPaid;
	}

	@Column(name = "SickLeaveUnPaid", precision = 9)
	public Double getSickLeaveUnPaid() {
		return this.sickLeaveUnPaid;
	}

	public void setSickLeaveUnPaid(Double sickLeaveUnPaid) {
		this.sickLeaveUnPaid = sickLeaveUnPaid;
	}

	@Column(name = "CasualLeaveUnPaid", precision = 9)
	public Double getCasualLeaveUnPaid() {
		return this.casualLeaveUnPaid;
	}

	public void setCasualLeaveUnPaid(Double casualLeaveUnPaid) {
		this.casualLeaveUnPaid = casualLeaveUnPaid;
	}

	@Column(name = "COFFLeaveUnPaid", precision = 9)
	public Double getCoffleaveUnPaid() {
		return this.coffleaveUnPaid;
	}

	public void setCoffleaveUnPaid(Double coffleaveUnPaid) {
		this.coffleaveUnPaid = coffleaveUnPaid;
	}

	@Column(name = "UnPaidHalfLeaves", precision = 9)
	public Double getUnPaidHalfLeaves() {
		return this.unPaidHalfLeaves;
	}

	public void setUnPaidHalfLeaves(Double unPaidHalfLeaves) {
		this.unPaidHalfLeaves = unPaidHalfLeaves;
	}

	@Column(name = "PayableDays", precision = 9)
	public Double getPayableDays() {
		return this.payableDays;
	}

	public void setPayableDays(Double payableDays) {
		this.payableDays = payableDays;
	}

	@Column(name = "LWP", precision = 9)
	public Double getLwp() {
		return this.lwp;
	}

	public void setLwp(Double lwp) {
		this.lwp = lwp;
	}

}
