package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * COffManagement generated by hbm2java
 */
@Entity
@Table(name = "c_off_management", catalog = "db_payroll", uniqueConstraints = @UniqueConstraint(columnNames = {
		"EmpId", "COffDate" }))
public class COffManagement implements java.io.Serializable {

	private Long coffId;
	private Date timeStamp;
	private Long empId;
	private Double coff;
	private Date coffDate;
	private String type;
	private Long insertedBy;
	private Date insertTs;
	private Long deletedBy;
	private Date deleteTs;
	private Long updatedBy;
	private Date updateTs;
	private Integer plantId;

	public COffManagement() {
	}

	public COffManagement(Long empId, Double coff, Date coffDate, String type,
			Long insertedBy, Date insertTs, Long deletedBy, Date deleteTs,
			Long updatedBy, Date updateTs, Integer plantId) {
		this.empId = empId;
		this.coff = coff;
		this.coffDate = coffDate;
		this.type = type;
		this.insertedBy = insertedBy;
		this.insertTs = insertTs;
		this.deletedBy = deletedBy;
		this.deleteTs = deleteTs;
		this.updatedBy = updatedBy;
		this.updateTs = updateTs;
		this.plantId = plantId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CoffId", unique = true, nullable = false)
	public Long getCoffId() {
		return this.coffId;
	}

	public void setCoffId(Long coffId) {
		this.coffId = coffId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "EmpId")
	public Long getEmpId() {
		return this.empId;
	}

	public void setEmpId(Long empId) {
		this.empId = empId;
	}

	@Column(name = "COff", precision = 9)
	public Double getCoff() {
		return this.coff;
	}

	public void setCoff(Double coff) {
		this.coff = coff;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COffDate", length = 19)
	public Date getCoffDate() {
		return this.coffDate;
	}

	public void setCoffDate(Date coffDate) {
		this.coffDate = coffDate;
	}

	@Column(name = "Type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "InsertedBy")
	public Long getInsertedBy() {
		return this.insertedBy;
	}

	public void setInsertedBy(Long insertedBy) {
		this.insertedBy = insertedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsertTs", length = 19)
	public Date getInsertTs() {
		return this.insertTs;
	}

	public void setInsertTs(Date insertTs) {
		this.insertTs = insertTs;
	}

	@Column(name = "DeletedBy")
	public Long getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(Long deletedBy) {
		this.deletedBy = deletedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeleteTs", length = 19)
	public Date getDeleteTs() {
		return this.deleteTs;
	}

	public void setDeleteTs(Date deleteTs) {
		this.deleteTs = deleteTs;
	}

	@Column(name = "UpdatedBy")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdateTs", length = 19)
	public Date getUpdateTs() {
		return this.updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

	@Column(name = "PlantId")
	public Integer getPlantId() {
		return this.plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
	}

}
