package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeMaster generated by hbm2java
 */
@Entity
@Table(name = "employee_master", catalog = "db_payroll")
public class EmployeeMaster implements java.io.Serializable {

	private Long empId;
	private UtilDepartment utilDepartment;
	private UtilDesignation utilDesignation;
	private MasterPlant masterPlant;
	private String title;
	private String name;
	private String marital;
	private String gender;
	private Date dob;
	private String address;
	private String city;
	private String country;
	private String state;
	private String pincode;
	private String contact1;
	private String contact2;
	private String phone;
	private String email;
	private String bankName;
	private String bankAccountNo;
	private String panNo;
	private String pfno;
	private String esino;
	private String taxNo;
	private Date dateOfBegining;
	private Date dateOfEnd;
	private Double basicPay;
	private Double overTimeWage;
	private Double workingHrPerDay;
	private Double hra;
	private Double da;
	private Double fda;
	private Double travelling;
	private Double attendance;
	private Double conveyance;
	private Double education;
	private Double otherAllowance;
	private Double loanEmi;
	private Double pf;
	private Double incomeTax;
	private Double professionTax;
	private Double esi;
	private Double festivalAdvEmi;
	private Double otherDeduction;
	private Integer modifiedBy;
	private String endOfDate;
	private Double medical;
	private Double specialAllowance;
	private String empImage;
	private Date createdDate;
	private Integer createdBy;
	private Date modifiedDate;
	private String jobStatus;
	private byte[] binaryEmpImage;
	private Byte isDeleted;
	private Double cellPhoneDeduction;
	private Double bonusAllowance;
	private String gradeDesignation;
	private Double medicalAllowance;
	private Double washingAllowance;
	private Double adhocAllowance;
	private Double arreastAllowance;
	private Double lwfdeduction;
	private String currentAddress;
	private String currentCity;
	private String currentCountry;
	private String currentState;
	private String currentPincode;
	private String bloodGroup;
	private String employeeType;

	public EmployeeMaster() {
	}

	public EmployeeMaster(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public EmployeeMaster(UtilDepartment utilDepartment,
			UtilDesignation utilDesignation, MasterPlant masterPlant,
			String title, String name, String marital, String gender, Date dob,
			String address, String city, String country, String state,
			String pincode, String contact1, String contact2, String phone,
			String email, String bankName, String bankAccountNo, String panNo,
			String pfno, String esino, String taxNo, Date dateOfBegining,
			Date dateOfEnd, Double basicPay, Double overTimeWage,
			Double workingHrPerDay, Double hra, Double da, Double fda,
			Double travelling, Double attendance, Double conveyance,
			Double education, Double otherAllowance, Double loanEmi, Double pf,
			Double incomeTax, Double professionTax, Double esi,
			Double festivalAdvEmi, Double otherDeduction, Integer modifiedBy,
			String endOfDate, Double medical, Double specialAllowance,
			String empImage, Date createdDate, Integer createdBy,
			Date modifiedDate, String jobStatus, byte[] binaryEmpImage,
			Byte isDeleted, Double cellPhoneDeduction, Double bonusAllowance,
			String gradeDesignation, Double medicalAllowance,
			Double washingAllowance, Double adhocAllowance,
			Double arreastAllowance, Double lwfdeduction,
			String currentAddress, String currentCity, String currentCountry,
			String currentState, String currentPincode, String bloodGroup,
			String employeeType) {
		this.utilDepartment = utilDepartment;
		this.utilDesignation = utilDesignation;
		this.masterPlant = masterPlant;
		this.title = title;
		this.name = name;
		this.marital = marital;
		this.gender = gender;
		this.dob = dob;
		this.address = address;
		this.city = city;
		this.country = country;
		this.state = state;
		this.pincode = pincode;
		this.contact1 = contact1;
		this.contact2 = contact2;
		this.phone = phone;
		this.email = email;
		this.bankName = bankName;
		this.bankAccountNo = bankAccountNo;
		this.panNo = panNo;
		this.pfno = pfno;
		this.esino = esino;
		this.taxNo = taxNo;
		this.dateOfBegining = dateOfBegining;
		this.dateOfEnd = dateOfEnd;
		this.basicPay = basicPay;
		this.overTimeWage = overTimeWage;
		this.workingHrPerDay = workingHrPerDay;
		this.hra = hra;
		this.da = da;
		this.fda = fda;
		this.travelling = travelling;
		this.attendance = attendance;
		this.conveyance = conveyance;
		this.education = education;
		this.otherAllowance = otherAllowance;
		this.loanEmi = loanEmi;
		this.pf = pf;
		this.incomeTax = incomeTax;
		this.professionTax = professionTax;
		this.esi = esi;
		this.festivalAdvEmi = festivalAdvEmi;
		this.otherDeduction = otherDeduction;
		this.modifiedBy = modifiedBy;
		this.endOfDate = endOfDate;
		this.medical = medical;
		this.specialAllowance = specialAllowance;
		this.empImage = empImage;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.jobStatus = jobStatus;
		this.binaryEmpImage = binaryEmpImage;
		this.isDeleted = isDeleted;
		this.cellPhoneDeduction = cellPhoneDeduction;
		this.bonusAllowance = bonusAllowance;
		this.gradeDesignation = gradeDesignation;
		this.medicalAllowance = medicalAllowance;
		this.washingAllowance = washingAllowance;
		this.adhocAllowance = adhocAllowance;
		this.arreastAllowance = arreastAllowance;
		this.lwfdeduction = lwfdeduction;
		this.currentAddress = currentAddress;
		this.currentCity = currentCity;
		this.currentCountry = currentCountry;
		this.currentState = currentState;
		this.currentPincode = currentPincode;
		this.bloodGroup = bloodGroup;
		this.employeeType = employeeType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EmpId", unique = true, nullable = false)
	public Long getEmpId() {
		return this.empId;
	}

	public void setEmpId(Long empId) {
		this.empId = empId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DepartmentId")
	public UtilDepartment getUtilDepartment() {
		return this.utilDepartment;
	}

	public void setUtilDepartment(UtilDepartment utilDepartment) {
		this.utilDepartment = utilDepartment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DesignationId")
	public UtilDesignation getUtilDesignation() {
		return this.utilDesignation;
	}

	public void setUtilDesignation(UtilDesignation utilDesignation) {
		this.utilDesignation = utilDesignation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PlantId")
	public MasterPlant getMasterPlant() {
		return this.masterPlant;
	}

	public void setMasterPlant(MasterPlant masterPlant) {
		this.masterPlant = masterPlant;
	}

	@Column(name = "Title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Name", length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Marital", length = 45)
	public String getMarital() {
		return this.marital;
	}

	public void setMarital(String marital) {
		this.marital = marital;
	}

	@Column(name = "Gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "Address", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "City", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "State", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Pincode", length = 45)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "Contact1", length = 10)
	public String getContact1() {
		return this.contact1;
	}

	public void setContact1(String contact1) {
		this.contact1 = contact1;
	}

	@Column(name = "Contact2", length = 10)
	public String getContact2() {
		return this.contact2;
	}

	public void setContact2(String contact2) {
		this.contact2 = contact2;
	}

	@Column(name = "Phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "BankName", length = 250)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "BankAccountNo", length = 45)
	public String getBankAccountNo() {
		return this.bankAccountNo;
	}

	public void setBankAccountNo(String bankAccountNo) {
		this.bankAccountNo = bankAccountNo;
	}

	@Column(name = "PanNo", length = 45)
	public String getPanNo() {
		return this.panNo;
	}

	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}

	@Column(name = "PFNo", length = 45)
	public String getPfno() {
		return this.pfno;
	}

	public void setPfno(String pfno) {
		this.pfno = pfno;
	}

	@Column(name = "ESINo", length = 45)
	public String getEsino() {
		return this.esino;
	}

	public void setEsino(String esino) {
		this.esino = esino;
	}

	@Column(name = "TaxNo", length = 45)
	public String getTaxNo() {
		return this.taxNo;
	}

	public void setTaxNo(String taxNo) {
		this.taxNo = taxNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateOfBegining", length = 10)
	public Date getDateOfBegining() {
		return this.dateOfBegining;
	}

	public void setDateOfBegining(Date dateOfBegining) {
		this.dateOfBegining = dateOfBegining;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateOfEnd", length = 19)
	public Date getDateOfEnd() {
		return this.dateOfEnd;
	}

	public void setDateOfEnd(Date dateOfEnd) {
		this.dateOfEnd = dateOfEnd;
	}

	@Column(name = "BasicPay", precision = 9)
	public Double getBasicPay() {
		return this.basicPay;
	}

	public void setBasicPay(Double basicPay) {
		this.basicPay = basicPay;
	}

	@Column(name = "OverTimeWage", precision = 9)
	public Double getOverTimeWage() {
		return this.overTimeWage;
	}

	public void setOverTimeWage(Double overTimeWage) {
		this.overTimeWage = overTimeWage;
	}

	@Column(name = "WorkingHrPerDay", precision = 9)
	public Double getWorkingHrPerDay() {
		return this.workingHrPerDay;
	}

	public void setWorkingHrPerDay(Double workingHrPerDay) {
		this.workingHrPerDay = workingHrPerDay;
	}

	@Column(name = "HRA", precision = 9)
	public Double getHra() {
		return this.hra;
	}

	public void setHra(Double hra) {
		this.hra = hra;
	}

	@Column(name = "DA", precision = 9)
	public Double getDa() {
		return this.da;
	}

	public void setDa(Double da) {
		this.da = da;
	}

	@Column(name = "FDA", precision = 9)
	public Double getFda() {
		return this.fda;
	}

	public void setFda(Double fda) {
		this.fda = fda;
	}

	@Column(name = "Travelling", precision = 9)
	public Double getTravelling() {
		return this.travelling;
	}

	public void setTravelling(Double travelling) {
		this.travelling = travelling;
	}

	@Column(name = "Attendance", precision = 9)
	public Double getAttendance() {
		return this.attendance;
	}

	public void setAttendance(Double attendance) {
		this.attendance = attendance;
	}

	@Column(name = "Conveyance", precision = 9)
	public Double getConveyance() {
		return this.conveyance;
	}

	public void setConveyance(Double conveyance) {
		this.conveyance = conveyance;
	}

	@Column(name = "Education", precision = 9)
	public Double getEducation() {
		return this.education;
	}

	public void setEducation(Double education) {
		this.education = education;
	}

	@Column(name = "OtherAllowance", precision = 9)
	public Double getOtherAllowance() {
		return this.otherAllowance;
	}

	public void setOtherAllowance(Double otherAllowance) {
		this.otherAllowance = otherAllowance;
	}

	@Column(name = "LoanEMI", precision = 9)
	public Double getLoanEmi() {
		return this.loanEmi;
	}

	public void setLoanEmi(Double loanEmi) {
		this.loanEmi = loanEmi;
	}

	@Column(name = "PF", precision = 9)
	public Double getPf() {
		return this.pf;
	}

	public void setPf(Double pf) {
		this.pf = pf;
	}

	@Column(name = "IncomeTax", precision = 9)
	public Double getIncomeTax() {
		return this.incomeTax;
	}

	public void setIncomeTax(Double incomeTax) {
		this.incomeTax = incomeTax;
	}

	@Column(name = "ProfessionTax", precision = 9)
	public Double getProfessionTax() {
		return this.professionTax;
	}

	public void setProfessionTax(Double professionTax) {
		this.professionTax = professionTax;
	}

	@Column(name = "ESI", precision = 9)
	public Double getEsi() {
		return this.esi;
	}

	public void setEsi(Double esi) {
		this.esi = esi;
	}

	@Column(name = "FestivalAdvEMI", precision = 9)
	public Double getFestivalAdvEmi() {
		return this.festivalAdvEmi;
	}

	public void setFestivalAdvEmi(Double festivalAdvEmi) {
		this.festivalAdvEmi = festivalAdvEmi;
	}

	@Column(name = "OtherDeduction", precision = 9)
	public Double getOtherDeduction() {
		return this.otherDeduction;
	}

	public void setOtherDeduction(Double otherDeduction) {
		this.otherDeduction = otherDeduction;
	}

	@Column(name = "ModifiedBy")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "EndOfDate", length = 45)
	public String getEndOfDate() {
		return this.endOfDate;
	}

	public void setEndOfDate(String endOfDate) {
		this.endOfDate = endOfDate;
	}

	@Column(name = "Medical", precision = 9)
	public Double getMedical() {
		return this.medical;
	}

	public void setMedical(Double medical) {
		this.medical = medical;
	}

	@Column(name = "SpecialAllowance", precision = 9)
	public Double getSpecialAllowance() {
		return this.specialAllowance;
	}

	public void setSpecialAllowance(Double specialAllowance) {
		this.specialAllowance = specialAllowance;
	}

	@Column(name = "EmpImage", length = 50)
	public String getEmpImage() {
		return this.empImage;
	}

	public void setEmpImage(String empImage) {
		this.empImage = empImage;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CreatedDate", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CreatedBy")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedDate", nullable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "JobStatus", length = 45)
	public String getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(String jobStatus) {
		this.jobStatus = jobStatus;
	}

	@Column(name = "BinaryEmpImage")
	public byte[] getBinaryEmpImage() {
		return this.binaryEmpImage;
	}

	public void setBinaryEmpImage(byte[] binaryEmpImage) {
		this.binaryEmpImage = binaryEmpImage;
	}

	@Column(name = "IsDeleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "CellPhoneDeduction", precision = 9)
	public Double getCellPhoneDeduction() {
		return this.cellPhoneDeduction;
	}

	public void setCellPhoneDeduction(Double cellPhoneDeduction) {
		this.cellPhoneDeduction = cellPhoneDeduction;
	}

	@Column(name = "BonusAllowance", precision = 9)
	public Double getBonusAllowance() {
		return this.bonusAllowance;
	}

	public void setBonusAllowance(Double bonusAllowance) {
		this.bonusAllowance = bonusAllowance;
	}

	@Column(name = "GradeDesignation", length = 45)
	public String getGradeDesignation() {
		return this.gradeDesignation;
	}

	public void setGradeDesignation(String gradeDesignation) {
		this.gradeDesignation = gradeDesignation;
	}

	@Column(name = "MedicalAllowance", precision = 9)
	public Double getMedicalAllowance() {
		return this.medicalAllowance;
	}

	public void setMedicalAllowance(Double medicalAllowance) {
		this.medicalAllowance = medicalAllowance;
	}

	@Column(name = "WashingAllowance", precision = 9)
	public Double getWashingAllowance() {
		return this.washingAllowance;
	}

	public void setWashingAllowance(Double washingAllowance) {
		this.washingAllowance = washingAllowance;
	}

	@Column(name = "AdhocAllowance", precision = 9)
	public Double getAdhocAllowance() {
		return this.adhocAllowance;
	}

	public void setAdhocAllowance(Double adhocAllowance) {
		this.adhocAllowance = adhocAllowance;
	}

	@Column(name = "ArreastAllowance", precision = 9)
	public Double getArreastAllowance() {
		return this.arreastAllowance;
	}

	public void setArreastAllowance(Double arreastAllowance) {
		this.arreastAllowance = arreastAllowance;
	}

	@Column(name = "LWFDeduction", precision = 9)
	public Double getLwfdeduction() {
		return this.lwfdeduction;
	}

	public void setLwfdeduction(Double lwfdeduction) {
		this.lwfdeduction = lwfdeduction;
	}

	@Column(name = "CurrentAddress", length = 500)
	public String getCurrentAddress() {
		return this.currentAddress;
	}

	public void setCurrentAddress(String currentAddress) {
		this.currentAddress = currentAddress;
	}

	@Column(name = "CurrentCity", length = 50)
	public String getCurrentCity() {
		return this.currentCity;
	}

	public void setCurrentCity(String currentCity) {
		this.currentCity = currentCity;
	}

	@Column(name = "CurrentCountry", length = 50)
	public String getCurrentCountry() {
		return this.currentCountry;
	}

	public void setCurrentCountry(String currentCountry) {
		this.currentCountry = currentCountry;
	}

	@Column(name = "CurrentState", length = 50)
	public String getCurrentState() {
		return this.currentState;
	}

	public void setCurrentState(String currentState) {
		this.currentState = currentState;
	}

	@Column(name = "CurrentPincode", length = 45)
	public String getCurrentPincode() {
		return this.currentPincode;
	}

	public void setCurrentPincode(String currentPincode) {
		this.currentPincode = currentPincode;
	}

	@Column(name = "BloodGroup", length = 10)
	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Column(name = "EmployeeType", length = 45)
	public String getEmployeeType() {
		return this.employeeType;
	}

	public void setEmployeeType(String employeeType) {
		this.employeeType = employeeType;
	}

}
