package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdMaster generated by hbm2java
 */
@Entity
@Table(name = "id_master", catalog = "db_payroll")
public class IdMaster implements java.io.Serializable {

	private Integer uniqueId;
	private Long lastGdn;
	private Long lastGrn;
	private Long lastSi;
	private Long lastPi;
	private Date finYear;
	private Date gdntimeStamp;
	private Date grntimeStamp;

	public IdMaster() {
	}

	public IdMaster(Long lastGdn, Long lastGrn, Long lastSi, Long lastPi,
			Date finYear, Date gdntimeStamp, Date grntimeStamp) {
		this.lastGdn = lastGdn;
		this.lastGrn = lastGrn;
		this.lastSi = lastSi;
		this.lastPi = lastPi;
		this.finYear = finYear;
		this.gdntimeStamp = gdntimeStamp;
		this.grntimeStamp = grntimeStamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UniqueId", unique = true, nullable = false)
	public Integer getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(Integer uniqueId) {
		this.uniqueId = uniqueId;
	}

	@Column(name = "LastGDN")
	public Long getLastGdn() {
		return this.lastGdn;
	}

	public void setLastGdn(Long lastGdn) {
		this.lastGdn = lastGdn;
	}

	@Column(name = "LastGRN")
	public Long getLastGrn() {
		return this.lastGrn;
	}

	public void setLastGrn(Long lastGrn) {
		this.lastGrn = lastGrn;
	}

	@Column(name = "LastSI")
	public Long getLastSi() {
		return this.lastSi;
	}

	public void setLastSi(Long lastSi) {
		this.lastSi = lastSi;
	}

	@Column(name = "LastPI")
	public Long getLastPi() {
		return this.lastPi;
	}

	public void setLastPi(Long lastPi) {
		this.lastPi = lastPi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FinYear", length = 19)
	public Date getFinYear() {
		return this.finYear;
	}

	public void setFinYear(Date finYear) {
		this.finYear = finYear;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GDNTimeStamp", length = 19)
	public Date getGdntimeStamp() {
		return this.gdntimeStamp;
	}

	public void setGdntimeStamp(Date gdntimeStamp) {
		this.gdntimeStamp = gdntimeStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GRNTimeStamp", length = 19)
	public Date getGrntimeStamp() {
		return this.grntimeStamp;
	}

	public void setGrntimeStamp(Date grntimeStamp) {
		this.grntimeStamp = grntimeStamp;
	}

}
