package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * LeaveTypeSetting generated by hbm2java
 */
@Entity
@Table(name = "leave_type_setting", catalog = "db_payroll", uniqueConstraints = @UniqueConstraint(columnNames = {
		"EmpId", "LeaveYear" }))
public class LeaveTypeSetting implements java.io.Serializable {

	private Long leaveId;
	private Long empId;
	private String leaveYear;
	private Double casualLeave;
	private Double balanceCl;
	private Double sickLeave;
	private Double balanceSl;
	private Double privilageLeave;
	private Double balancePl;
	private Double compansatoryLeave;
	private Double balanceCoff;
	private Boolean insertedBy;
	private Date insertTs;
	private Boolean isDeleted;
	private Integer plantId;

	public LeaveTypeSetting() {
	}

	public LeaveTypeSetting(Long empId, String leaveYear, Double casualLeave,
			Double balanceCl, Double sickLeave, Double balanceSl,
			Double privilageLeave, Double balancePl, Double compansatoryLeave,
			Double balanceCoff, Boolean insertedBy, Date insertTs,
			Boolean isDeleted, Integer plantId) {
		this.empId = empId;
		this.leaveYear = leaveYear;
		this.casualLeave = casualLeave;
		this.balanceCl = balanceCl;
		this.sickLeave = sickLeave;
		this.balanceSl = balanceSl;
		this.privilageLeave = privilageLeave;
		this.balancePl = balancePl;
		this.compansatoryLeave = compansatoryLeave;
		this.balanceCoff = balanceCoff;
		this.insertedBy = insertedBy;
		this.insertTs = insertTs;
		this.isDeleted = isDeleted;
		this.plantId = plantId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LeaveId", unique = true, nullable = false)
	public Long getLeaveId() {
		return this.leaveId;
	}

	public void setLeaveId(Long leaveId) {
		this.leaveId = leaveId;
	}

	@Column(name = "EmpId")
	public Long getEmpId() {
		return this.empId;
	}

	public void setEmpId(Long empId) {
		this.empId = empId;
	}

	@Column(name = "LeaveYear", length = 45)
	public String getLeaveYear() {
		return this.leaveYear;
	}

	public void setLeaveYear(String leaveYear) {
		this.leaveYear = leaveYear;
	}

	@Column(name = "CasualLeave", precision = 9)
	public Double getCasualLeave() {
		return this.casualLeave;
	}

	public void setCasualLeave(Double casualLeave) {
		this.casualLeave = casualLeave;
	}

	@Column(name = "BalanceCL", precision = 9)
	public Double getBalanceCl() {
		return this.balanceCl;
	}

	public void setBalanceCl(Double balanceCl) {
		this.balanceCl = balanceCl;
	}

	@Column(name = "SickLeave", precision = 9)
	public Double getSickLeave() {
		return this.sickLeave;
	}

	public void setSickLeave(Double sickLeave) {
		this.sickLeave = sickLeave;
	}

	@Column(name = "BalanceSL", precision = 9)
	public Double getBalanceSl() {
		return this.balanceSl;
	}

	public void setBalanceSl(Double balanceSl) {
		this.balanceSl = balanceSl;
	}

	@Column(name = "PrivilageLeave", precision = 9)
	public Double getPrivilageLeave() {
		return this.privilageLeave;
	}

	public void setPrivilageLeave(Double privilageLeave) {
		this.privilageLeave = privilageLeave;
	}

	@Column(name = "BalancePL", precision = 9)
	public Double getBalancePl() {
		return this.balancePl;
	}

	public void setBalancePl(Double balancePl) {
		this.balancePl = balancePl;
	}

	@Column(name = "CompansatoryLeave", precision = 9)
	public Double getCompansatoryLeave() {
		return this.compansatoryLeave;
	}

	public void setCompansatoryLeave(Double compansatoryLeave) {
		this.compansatoryLeave = compansatoryLeave;
	}

	@Column(name = "BalanceCOFF", precision = 9)
	public Double getBalanceCoff() {
		return this.balanceCoff;
	}

	public void setBalanceCoff(Double balanceCoff) {
		this.balanceCoff = balanceCoff;
	}

	@Column(name = "InsertedBy")
	public Boolean getInsertedBy() {
		return this.insertedBy;
	}

	public void setInsertedBy(Boolean insertedBy) {
		this.insertedBy = insertedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsertTs", length = 19)
	public Date getInsertTs() {
		return this.insertTs;
	}

	public void setInsertTs(Date insertTs) {
		this.insertTs = insertTs;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "PlantId")
	public Integer getPlantId() {
		return this.plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
	}

}
