package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MasterUser generated by hbm2java
 */
@Entity
@Table(name = "master_user", catalog = "db_payroll", uniqueConstraints = @UniqueConstraint(columnNames = "UserName"))
public class MasterUser implements java.io.Serializable {

	private Integer id;
	private Date timeStamp;
	private MasterUser masterUser;
	private String userName;
	private String password;
	private Integer employeeId;
	private String employeeName;
	private Byte isActive;
	private String type;
	private int insertedBy;
	private Boolean isDeleted;
	private Integer plantId;
	private Set masterOrganizations = new HashSet(0);
	private Set masterUsers = new HashSet(0);
	private Set masterCompanies = new HashSet(0);
	private Set masterPlants = new HashSet(0);

	public MasterUser() {
	}

	public MasterUser(MasterUser masterUser, String userName, String password,
			int insertedBy) {
		this.masterUser = masterUser;
		this.userName = userName;
		this.password = password;
		this.insertedBy = insertedBy;
	}

	public MasterUser(MasterUser masterUser, String userName, String password,
			Integer employeeId, String employeeName, Byte isActive,
			String type, int insertedBy, Boolean isDeleted, Integer plantId,
			Set masterOrganizations, Set masterUsers, Set masterCompanies,
			Set masterPlants) {
		this.masterUser = masterUser;
		this.userName = userName;
		this.password = password;
		this.employeeId = employeeId;
		this.employeeName = employeeName;
		this.isActive = isActive;
		this.type = type;
		this.insertedBy = insertedBy;
		this.isDeleted = isDeleted;
		this.plantId = plantId;
		this.masterOrganizations = masterOrganizations;
		this.masterUsers = masterUsers;
		this.masterCompanies = masterCompanies;
		this.masterPlants = masterPlants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId", nullable = false)
	public MasterUser getMasterUser() {
		return this.masterUser;
	}

	public void setMasterUser(MasterUser masterUser) {
		this.masterUser = masterUser;
	}

	@Column(name = "UserName", unique = true, nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EmployeeId")
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "EmployeeName", length = 100)
	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	@Column(name = "IsActive")
	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	@Column(name = "Type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "InsertedBy", nullable = false)
	public int getInsertedBy() {
		return this.insertedBy;
	}

	public void setInsertedBy(int insertedBy) {
		this.insertedBy = insertedBy;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "PlantId")
	public Integer getPlantId() {
		return this.plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterUser")
	public Set getMasterOrganizations() {
		return this.masterOrganizations;
	}

	public void setMasterOrganizations(Set masterOrganizations) {
		this.masterOrganizations = masterOrganizations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterUser")
	public Set getMasterUsers() {
		return this.masterUsers;
	}

	public void setMasterUsers(Set masterUsers) {
		this.masterUsers = masterUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterUser")
	public Set getMasterCompanies() {
		return this.masterCompanies;
	}

	public void setMasterCompanies(Set masterCompanies) {
		this.masterCompanies = masterCompanies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterUser")
	public Set getMasterPlants() {
		return this.masterPlants;
	}

	public void setMasterPlants(Set masterPlants) {
		this.masterPlants = masterPlants;
	}

}
