package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MasterPrivelegesModules generated by hbm2java
 */
@Entity
@Table(name = "master_priveleges_modules", catalog = "db_payroll")
public class MasterPrivelegesModules implements java.io.Serializable {

	private Integer moduleId;
	private String module;
	private String moduleHome;
	private String faClass;

	public MasterPrivelegesModules() {
	}

	public MasterPrivelegesModules(String module, String moduleHome,
			String faClass) {
		this.module = module;
		this.moduleHome = moduleHome;
		this.faClass = faClass;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ModuleId", unique = true, nullable = false)
	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "Module", length = 45)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "ModuleHome", length = 200)
	public String getModuleHome() {
		return this.moduleHome;
	}

	public void setModuleHome(String moduleHome) {
		this.moduleHome = moduleHome;
	}

	@Column(name = "FaClass", length = 45)
	public String getFaClass() {
		return this.faClass;
	}

	public void setFaClass(String faClass) {
		this.faClass = faClass;
	}

}
