package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MasterCompany generated by hbm2java
 */
@Entity
@Table(name = "master_company", catalog = "db_payroll", uniqueConstraints = @UniqueConstraint(columnNames = "CompanyName"))
public class MasterCompany implements java.io.Serializable {

	private Integer companyId; // update 19.12_01
	private Date timeStamp;
	private MasterOrganization masterOrganization;
	private MasterUser masterUser;
	private String companyName;
	private Date establishmentDate;
	private byte[] companyLogo;
	private Set masterPlants = new HashSet(0);

	public MasterCompany() {
	}

	public MasterCompany(MasterOrganization masterOrganization,
			MasterUser masterUser, String companyName) {
		this.masterOrganization = masterOrganization;
		this.masterUser = masterUser;
		this.companyName = companyName;
	}

	public MasterCompany(MasterOrganization masterOrganization,
			MasterUser masterUser, String companyName, Date establishmentDate,
			byte[] companyLogo, Set masterPlants) {
		this.masterOrganization = masterOrganization;
		this.masterUser = masterUser;
		this.companyName = companyName;
		this.establishmentDate = establishmentDate;
		this.companyLogo = companyLogo;
		this.masterPlants = masterPlants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CompanyId", unique = true, nullable = false)
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OrgId", nullable = false)
	public MasterOrganization getMasterOrganization() {
		return this.masterOrganization;
	}

	public void setMasterOrganization(MasterOrganization masterOrganization) {
		this.masterOrganization = masterOrganization;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId", nullable = false)
	public MasterUser getMasterUser() {
		return this.masterUser;
	}

	public void setMasterUser(MasterUser masterUser) {
		this.masterUser = masterUser;
	}

	@Column(name = "CompanyName", unique = true, nullable = false, length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EstablishmentDate", length = 10)
	public Date getEstablishmentDate() {
		return this.establishmentDate;
	}

	public void setEstablishmentDate(Date establishmentDate) {
		this.establishmentDate = establishmentDate;
	}

	@Column(name = "CompanyLogo")
	public byte[] getCompanyLogo() {
		return this.companyLogo;
	}

	public void setCompanyLogo(byte[] companyLogo) {
		this.companyLogo = companyLogo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterCompany")
	public Set getMasterPlants() {
		return this.masterPlants;
	}

	public void setMasterPlants(Set masterPlants) {
		this.masterPlants = masterPlants;
	}

}
