package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MasterOrganization generated by hbm2java
 */
@Entity
@Table(name = "master_organization", catalog = "db_payroll", uniqueConstraints = @UniqueConstraint(columnNames = "OrgName"))
public class MasterOrganization implements java.io.Serializable {

	private Integer orgId;
	private Date timeStamp;
	private MasterUser masterUser;
	private String orgName;
	private Date establishmentDate;
	private String description;
	private Integer isDeleted;
	private Integer isActive;
	private Set masterCompanies = new HashSet(0);

	public MasterOrganization() {
	}

	public MasterOrganization(MasterUser masterUser, String orgName) {
		this.masterUser = masterUser;
		this.orgName = orgName;
	}

	public MasterOrganization(MasterUser masterUser, String orgName,
			Date establishmentDate, String description, Integer isDeleted,
			Integer isActive, Set masterCompanies) {
		this.masterUser = masterUser;
		this.orgName = orgName;
		this.establishmentDate = establishmentDate;
		this.description = description;
		this.isDeleted = isDeleted;
		this.isActive = isActive;
		this.masterCompanies = masterCompanies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OrgId", unique = true, nullable = false)
	public Integer getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId", nullable = false)
	public MasterUser getMasterUser() {
		return this.masterUser;
	}

	public void setMasterUser(MasterUser masterUser) {
		this.masterUser = masterUser;
	}

	@Column(name = "OrgName", unique = true, nullable = false, length = 60)
	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EstablishmentDate", length = 10)
	public Date getEstablishmentDate() {
		return this.establishmentDate;
	}

	public void setEstablishmentDate(Date establishmentDate) {
		this.establishmentDate = establishmentDate;
	}

	@Column(name = "Description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "IsDeleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "IsActive")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterOrganization")
	public Set getMasterCompanies() {
		return this.masterCompanies;
	}

	public void setMasterCompanies(Set masterCompanies) {
		this.masterCompanies = masterCompanies;
	}

}
