package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MasterUserPriveleges generated by hbm2java
 */
@Entity
@Table(name = "master_user_priveleges", catalog = "db_payroll")
public class MasterUserPriveleges implements java.io.Serializable {

	private Integer privelegeId;
	private Integer userId;
	private Integer moduleId;

	public MasterUserPriveleges() {
	}

	public MasterUserPriveleges(Integer userId, Integer moduleId) {
		this.userId = userId;
		this.moduleId = moduleId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PrivelegeId", unique = true, nullable = false)
	public Integer getPrivelegeId() {
		return this.privelegeId;
	}

	public void setPrivelegeId(Integer privelegeId) {
		this.privelegeId = privelegeId;
	}

	@Column(name = "UserId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "ModuleId")
	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

}
