package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * SalSlipMaster generated by hbm2java
 */
@Entity
@Table(name = "sal_slip_master", catalog = "db_payroll", uniqueConstraints = @UniqueConstraint(columnNames = {
		"EmpId", "SlipMonth", "SlipYear" }))
public class SalSlipMaster implements java.io.Serializable {

	private Integer salSlipId;
	private Date timeStamp;
	private Long empId;
	private String empName;
	private String slipMonth;
	private String slipYear;
	private Double alHra;
	private Double alDa;
	private Double alFda;
	private Double alTravelling;
	private Double alAttendance;
	private Double alConveyance;
	private Double alEducation;
	private Double alBonus;
	private Double alMedical;
	private Double alWashing;
	private Double alAdhoc;
	private Double alArreasal;
	private Double alOthers;
	private Double dePf;
	private Double deEsi;
	private Double deIncomeTax;
	private Double deLoanEmi;
	private Double deProfTax;
	private Double deFestivalAdvEmi;
	private Double deCellPhone;
	private Double deLwf;
	private Double deOthers;
	private Double monthDays;
	private Double workingDays;
	private Double presentDays;
	private Double payableDays;
	private Double lwp;
	private Double absentDays;
	private Double paidWeekOff;
	private Double paidLeaves;
	private Double unpaidLeaves;
	private Double paidHolidays;
	private Double unPaidHolidays;
	private Double paidHalfDay;
	private Double unpaidHalfDay;
	private Double paidLateMarkDays;
	private Double ottotalHr;
	private Double ottotalMoney;
	private Double lessHrs;
	private Double lessRs;
	private Double trueBasic;
	private Double basicPay;
	private Double totalDeduction;
	private Double totalAllowance;
	private Double netPayment;
	private Double grossSalary;
	private Double ctc;
	private Boolean isDeleted;

	public SalSlipMaster() {
	}

	public SalSlipMaster(Long empId, String empName, String slipMonth,
			String slipYear, Double alHra, Double alDa, Double alFda,
			Double alTravelling, Double alAttendance, Double alConveyance,
			Double alEducation, Double alBonus, Double alMedical,
			Double alWashing, Double alAdhoc, Double alArreasal,
			Double alOthers, Double dePf, Double deEsi, Double deIncomeTax,
			Double deLoanEmi, Double deProfTax, Double deFestivalAdvEmi,
			Double deCellPhone, Double deLwf, Double deOthers,
			Double monthDays, Double workingDays, Double presentDays,
			Double payableDays, Double lwp, Double absentDays,
			Double paidWeekOff, Double paidLeaves, Double unpaidLeaves,
			Double paidHolidays, Double unPaidHolidays, Double paidHalfDay,
			Double unpaidHalfDay, Double paidLateMarkDays, Double ottotalHr,
			Double ottotalMoney, Double lessHrs, Double lessRs,
			Double trueBasic, Double basicPay, Double totalDeduction,
			Double totalAllowance, Double netPayment, Double grossSalary,
			Double ctc, Boolean isDeleted) {
		this.empId = empId;
		this.empName = empName;
		this.slipMonth = slipMonth;
		this.slipYear = slipYear;
		this.alHra = alHra;
		this.alDa = alDa;
		this.alFda = alFda;
		this.alTravelling = alTravelling;
		this.alAttendance = alAttendance;
		this.alConveyance = alConveyance;
		this.alEducation = alEducation;
		this.alBonus = alBonus;
		this.alMedical = alMedical;
		this.alWashing = alWashing;
		this.alAdhoc = alAdhoc;
		this.alArreasal = alArreasal;
		this.alOthers = alOthers;
		this.dePf = dePf;
		this.deEsi = deEsi;
		this.deIncomeTax = deIncomeTax;
		this.deLoanEmi = deLoanEmi;
		this.deProfTax = deProfTax;
		this.deFestivalAdvEmi = deFestivalAdvEmi;
		this.deCellPhone = deCellPhone;
		this.deLwf = deLwf;
		this.deOthers = deOthers;
		this.monthDays = monthDays;
		this.workingDays = workingDays;
		this.presentDays = presentDays;
		this.payableDays = payableDays;
		this.lwp = lwp;
		this.absentDays = absentDays;
		this.paidWeekOff = paidWeekOff;
		this.paidLeaves = paidLeaves;
		this.unpaidLeaves = unpaidLeaves;
		this.paidHolidays = paidHolidays;
		this.unPaidHolidays = unPaidHolidays;
		this.paidHalfDay = paidHalfDay;
		this.unpaidHalfDay = unpaidHalfDay;
		this.paidLateMarkDays = paidLateMarkDays;
		this.ottotalHr = ottotalHr;
		this.ottotalMoney = ottotalMoney;
		this.lessHrs = lessHrs;
		this.lessRs = lessRs;
		this.trueBasic = trueBasic;
		this.basicPay = basicPay;
		this.totalDeduction = totalDeduction;
		this.totalAllowance = totalAllowance;
		this.netPayment = netPayment;
		this.grossSalary = grossSalary;
		this.ctc = ctc;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SalSlipId", unique = true, nullable = false)
	public Integer getSalSlipId() {
		return this.salSlipId;
	}

	public void setSalSlipId(Integer salSlipId) {
		this.salSlipId = salSlipId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", nullable = false, length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "EmpId")
	public Long getEmpId() {
		return this.empId;
	}

	public void setEmpId(Long empId) {
		this.empId = empId;
	}

	@Column(name = "EmpName", length = 100)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "SlipMonth", length = 45)
	public String getSlipMonth() {
		return this.slipMonth;
	}

	public void setSlipMonth(String slipMonth) {
		this.slipMonth = slipMonth;
	}

	@Column(name = "SlipYear", length = 45)
	public String getSlipYear() {
		return this.slipYear;
	}

	public void setSlipYear(String slipYear) {
		this.slipYear = slipYear;
	}

	@Column(name = "AlHRA", precision = 9)
	public Double getAlHra() {
		return this.alHra;
	}

	public void setAlHra(Double alHra) {
		this.alHra = alHra;
	}

	@Column(name = "AlDA", precision = 9)
	public Double getAlDa() {
		return this.alDa;
	}

	public void setAlDa(Double alDa) {
		this.alDa = alDa;
	}

	@Column(name = "AlFDA", precision = 9)
	public Double getAlFda() {
		return this.alFda;
	}

	public void setAlFda(Double alFda) {
		this.alFda = alFda;
	}

	@Column(name = "AlTravelling", precision = 9)
	public Double getAlTravelling() {
		return this.alTravelling;
	}

	public void setAlTravelling(Double alTravelling) {
		this.alTravelling = alTravelling;
	}

	@Column(name = "AlAttendance", precision = 9)
	public Double getAlAttendance() {
		return this.alAttendance;
	}

	public void setAlAttendance(Double alAttendance) {
		this.alAttendance = alAttendance;
	}

	@Column(name = "AlConveyance", precision = 9)
	public Double getAlConveyance() {
		return this.alConveyance;
	}

	public void setAlConveyance(Double alConveyance) {
		this.alConveyance = alConveyance;
	}

	@Column(name = "AlEducation", precision = 9)
	public Double getAlEducation() {
		return this.alEducation;
	}

	public void setAlEducation(Double alEducation) {
		this.alEducation = alEducation;
	}

	@Column(name = "AlBonus", precision = 9)
	public Double getAlBonus() {
		return this.alBonus;
	}

	public void setAlBonus(Double alBonus) {
		this.alBonus = alBonus;
	}

	@Column(name = "AlMedical", precision = 9)
	public Double getAlMedical() {
		return this.alMedical;
	}

	public void setAlMedical(Double alMedical) {
		this.alMedical = alMedical;
	}

	@Column(name = "AlWashing", precision = 9)
	public Double getAlWashing() {
		return this.alWashing;
	}

	public void setAlWashing(Double alWashing) {
		this.alWashing = alWashing;
	}

	@Column(name = "AlAdhoc", precision = 9)
	public Double getAlAdhoc() {
		return this.alAdhoc;
	}

	public void setAlAdhoc(Double alAdhoc) {
		this.alAdhoc = alAdhoc;
	}

	@Column(name = "AlArreasal", precision = 9)
	public Double getAlArreasal() {
		return this.alArreasal;
	}

	public void setAlArreasal(Double alArreasal) {
		this.alArreasal = alArreasal;
	}

	@Column(name = "AlOthers", precision = 9)
	public Double getAlOthers() {
		return this.alOthers;
	}

	public void setAlOthers(Double alOthers) {
		this.alOthers = alOthers;
	}

	@Column(name = "DePF", precision = 9)
	public Double getDePf() {
		return this.dePf;
	}

	public void setDePf(Double dePf) {
		this.dePf = dePf;
	}

	@Column(name = "DeESI", precision = 9)
	public Double getDeEsi() {
		return this.deEsi;
	}

	public void setDeEsi(Double deEsi) {
		this.deEsi = deEsi;
	}

	@Column(name = "DeIncomeTax", precision = 9)
	public Double getDeIncomeTax() {
		return this.deIncomeTax;
	}

	public void setDeIncomeTax(Double deIncomeTax) {
		this.deIncomeTax = deIncomeTax;
	}

	@Column(name = "DeLoanEMI", precision = 9)
	public Double getDeLoanEmi() {
		return this.deLoanEmi;
	}

	public void setDeLoanEmi(Double deLoanEmi) {
		this.deLoanEmi = deLoanEmi;
	}

	@Column(name = "DeProfTax", precision = 9)
	public Double getDeProfTax() {
		return this.deProfTax;
	}

	public void setDeProfTax(Double deProfTax) {
		this.deProfTax = deProfTax;
	}

	@Column(name = "DeFestivalAdvEMI", precision = 9)
	public Double getDeFestivalAdvEmi() {
		return this.deFestivalAdvEmi;
	}

	public void setDeFestivalAdvEmi(Double deFestivalAdvEmi) {
		this.deFestivalAdvEmi = deFestivalAdvEmi;
	}

	@Column(name = "DeCellPhone", precision = 9)
	public Double getDeCellPhone() {
		return this.deCellPhone;
	}

	public void setDeCellPhone(Double deCellPhone) {
		this.deCellPhone = deCellPhone;
	}

	@Column(name = "DeLWF", precision = 9)
	public Double getDeLwf() {
		return this.deLwf;
	}

	public void setDeLwf(Double deLwf) {
		this.deLwf = deLwf;
	}

	@Column(name = "DeOthers", precision = 9)
	public Double getDeOthers() {
		return this.deOthers;
	}

	public void setDeOthers(Double deOthers) {
		this.deOthers = deOthers;
	}

	@Column(name = "MonthDays", precision = 9)
	public Double getMonthDays() {
		return this.monthDays;
	}

	public void setMonthDays(Double monthDays) {
		this.monthDays = monthDays;
	}

	@Column(name = "WorkingDays", precision = 9)
	public Double getWorkingDays() {
		return this.workingDays;
	}

	public void setWorkingDays(Double workingDays) {
		this.workingDays = workingDays;
	}

	@Column(name = "PresentDays", precision = 9)
	public Double getPresentDays() {
		return this.presentDays;
	}

	public void setPresentDays(Double presentDays) {
		this.presentDays = presentDays;
	}

	@Column(name = "PayableDays", precision = 9)
	public Double getPayableDays() {
		return this.payableDays;
	}

	public void setPayableDays(Double payableDays) {
		this.payableDays = payableDays;
	}

	@Column(name = "LWP", precision = 9)
	public Double getLwp() {
		return this.lwp;
	}

	public void setLwp(Double lwp) {
		this.lwp = lwp;
	}

	@Column(name = "AbsentDays", precision = 9)
	public Double getAbsentDays() {
		return this.absentDays;
	}

	public void setAbsentDays(Double absentDays) {
		this.absentDays = absentDays;
	}

	@Column(name = "PaidWeekOff", precision = 9)
	public Double getPaidWeekOff() {
		return this.paidWeekOff;
	}

	public void setPaidWeekOff(Double paidWeekOff) {
		this.paidWeekOff = paidWeekOff;
	}

	@Column(name = "PaidLeaves", precision = 9)
	public Double getPaidLeaves() {
		return this.paidLeaves;
	}

	public void setPaidLeaves(Double paidLeaves) {
		this.paidLeaves = paidLeaves;
	}

	@Column(name = "UnpaidLeaves", precision = 9)
	public Double getUnpaidLeaves() {
		return this.unpaidLeaves;
	}

	public void setUnpaidLeaves(Double unpaidLeaves) {
		this.unpaidLeaves = unpaidLeaves;
	}

	@Column(name = "PaidHolidays", precision = 9)
	public Double getPaidHolidays() {
		return this.paidHolidays;
	}

	public void setPaidHolidays(Double paidHolidays) {
		this.paidHolidays = paidHolidays;
	}

	@Column(name = "UnPaidHolidays", precision = 9)
	public Double getUnPaidHolidays() {
		return this.unPaidHolidays;
	}

	public void setUnPaidHolidays(Double unPaidHolidays) {
		this.unPaidHolidays = unPaidHolidays;
	}

	@Column(name = "PaidHalfDay", precision = 9)
	public Double getPaidHalfDay() {
		return this.paidHalfDay;
	}

	public void setPaidHalfDay(Double paidHalfDay) {
		this.paidHalfDay = paidHalfDay;
	}

	@Column(name = "UnpaidHalfDay", precision = 9)
	public Double getUnpaidHalfDay() {
		return this.unpaidHalfDay;
	}

	public void setUnpaidHalfDay(Double unpaidHalfDay) {
		this.unpaidHalfDay = unpaidHalfDay;
	}

	@Column(name = "PaidLateMarkDays", precision = 9)
	public Double getPaidLateMarkDays() {
		return this.paidLateMarkDays;
	}

	public void setPaidLateMarkDays(Double paidLateMarkDays) {
		this.paidLateMarkDays = paidLateMarkDays;
	}

	@Column(name = "OTTotalHr", precision = 9)
	public Double getOttotalHr() {
		return this.ottotalHr;
	}

	public void setOttotalHr(Double ottotalHr) {
		this.ottotalHr = ottotalHr;
	}

	@Column(name = "OTTotalMoney", precision = 9)
	public Double getOttotalMoney() {
		return this.ottotalMoney;
	}

	public void setOttotalMoney(Double ottotalMoney) {
		this.ottotalMoney = ottotalMoney;
	}

	@Column(name = "LessHrs", precision = 9)
	public Double getLessHrs() {
		return this.lessHrs;
	}

	public void setLessHrs(Double lessHrs) {
		this.lessHrs = lessHrs;
	}

	@Column(name = "LessRs", precision = 9)
	public Double getLessRs() {
		return this.lessRs;
	}

	public void setLessRs(Double lessRs) {
		this.lessRs = lessRs;
	}

	@Column(name = "TrueBasic", precision = 9)
	public Double getTrueBasic() {
		return this.trueBasic;
	}

	public void setTrueBasic(Double trueBasic) {
		this.trueBasic = trueBasic;
	}

	@Column(name = "BasicPay", precision = 9)
	public Double getBasicPay() {
		return this.basicPay;
	}

	public void setBasicPay(Double basicPay) {
		this.basicPay = basicPay;
	}

	@Column(name = "TotalDeduction", precision = 9)
	public Double getTotalDeduction() {
		return this.totalDeduction;
	}

	public void setTotalDeduction(Double totalDeduction) {
		this.totalDeduction = totalDeduction;
	}

	@Column(name = "TotalAllowance", precision = 9)
	public Double getTotalAllowance() {
		return this.totalAllowance;
	}

	public void setTotalAllowance(Double totalAllowance) {
		this.totalAllowance = totalAllowance;
	}

	@Column(name = "NetPayment", precision = 9)
	public Double getNetPayment() {
		return this.netPayment;
	}

	public void setNetPayment(Double netPayment) {
		this.netPayment = netPayment;
	}

	@Column(name = "GrossSalary", precision = 9)
	public Double getGrossSalary() {
		return this.grossSalary;
	}

	public void setGrossSalary(Double grossSalary) {
		this.grossSalary = grossSalary;
	}

	@Column(name = "CTC", precision = 9)
	public Double getCtc() {
		return this.ctc;
	}

	public void setCtc(Double ctc) {
		this.ctc = ctc;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
