package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SettingShiftType generated by hbm2java
 */
@Entity
@Table(name = "setting_shift_type", catalog = "db_payroll")
public class SettingShiftType implements java.io.Serializable {

	private Long shiftId;
	private String shiftName;
	private String fromTime;
	private String toTime;
	private String halfDay;
	private Double duration;
	private BigDecimal extraPay;
	private String modifiedBy;
	private Date modifiedDate;
	private Boolean isSheduled;
	private Integer plantId;
	private Set shiftAllocations = new HashSet(0);

	public SettingShiftType() {
	}

	public SettingShiftType(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public SettingShiftType(String shiftName, String fromTime, String toTime,
			String halfDay, Double duration, BigDecimal extraPay,
			String modifiedBy, Date modifiedDate, Boolean isSheduled,
			Integer plantId, Set shiftAllocations) {
		this.shiftName = shiftName;
		this.fromTime = fromTime;
		this.toTime = toTime;
		this.halfDay = halfDay;
		this.duration = duration;
		this.extraPay = extraPay;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.isSheduled = isSheduled;
		this.plantId = plantId;
		this.shiftAllocations = shiftAllocations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ShiftId", unique = true, nullable = false)
	public Long getShiftId() {
		return this.shiftId;
	}

	public void setShiftId(Long shiftId) {
		this.shiftId = shiftId;
	}

	@Column(name = "ShiftName", length = 45)
	public String getShiftName() {
		return this.shiftName;
	}

	public void setShiftName(String shiftName) {
		this.shiftName = shiftName;
	}

	@Column(name = "FromTime", length = 45)
	public String getFromTime() {
		return this.fromTime;
	}

	public void setFromTime(String fromTime) {
		this.fromTime = fromTime;
	}

	@Column(name = "ToTime", length = 45)
	public String getToTime() {
		return this.toTime;
	}

	public void setToTime(String toTime) {
		this.toTime = toTime;
	}

	@Column(name = "HalfDay", length = 45)
	public String getHalfDay() {
		return this.halfDay;
	}

	public void setHalfDay(String halfDay) {
		this.halfDay = halfDay;
	}

	@Column(name = "Duration", precision = 9)
	public Double getDuration() {
		return this.duration;
	}

	public void setDuration(Double duration) {
		this.duration = duration;
	}

	@Column(name = "ExtraPay", precision = 9)
	public BigDecimal getExtraPay() {
		return this.extraPay;
	}

	public void setExtraPay(BigDecimal extraPay) {
		this.extraPay = extraPay;
	}

	@Column(name = "ModifiedBy", length = 45)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedDate", nullable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "IsSheduled")
	public Boolean getIsSheduled() {
		return this.isSheduled;
	}

	public void setIsSheduled(Boolean isSheduled) {
		this.isSheduled = isSheduled;
	}

	@Column(name = "PlantId")
	public Integer getPlantId() {
		return this.plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "settingShiftType")
	public Set getShiftAllocations() {
		return this.shiftAllocations;
	}

	public void setShiftAllocations(Set shiftAllocations) {
		this.shiftAllocations = shiftAllocations;
	}

}
