package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SettingLeaveType generated by hbm2java
 */
@Entity
@Table(name = "setting_leave_type", catalog = "db_payroll")
public class SettingLeaveType implements java.io.Serializable {

	private String leaveId;
	private String leave;
	private String isPaid;
	private String isBalance;
	private String isEnCash;
	private Integer leaveQty;
	private String modifiedBy;
	private Date modifiedDate;

	public SettingLeaveType() {
	}

	public SettingLeaveType(String leaveId, Date modifiedDate) {
		this.leaveId = leaveId;
		this.modifiedDate = modifiedDate;
	}

	public SettingLeaveType(String leaveId, String leave, String isPaid,
			String isBalance, String isEnCash, Integer leaveQty,
			String modifiedBy, Date modifiedDate) {
		this.leaveId = leaveId;
		this.leave = leave;
		this.isPaid = isPaid;
		this.isBalance = isBalance;
		this.isEnCash = isEnCash;
		this.leaveQty = leaveQty;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
	}

	@Id
	@Column(name = "LeaveId", unique = true, nullable = false, length = 10)
	public String getLeaveId() {
		return this.leaveId;
	}

	public void setLeaveId(String leaveId) {
		this.leaveId = leaveId;
	}

	@Column(name = "Leave", length = 45)
	public String getLeave() {
		return this.leave;
	}

	public void setLeave(String leave) {
		this.leave = leave;
	}

	@Column(name = "IsPaid", length = 10)
	public String getIsPaid() {
		return this.isPaid;
	}

	public void setIsPaid(String isPaid) {
		this.isPaid = isPaid;
	}

	@Column(name = "IsBalance", length = 10)
	public String getIsBalance() {
		return this.isBalance;
	}

	public void setIsBalance(String isBalance) {
		this.isBalance = isBalance;
	}

	@Column(name = "IsEnCash", length = 10)
	public String getIsEnCash() {
		return this.isEnCash;
	}

	public void setIsEnCash(String isEnCash) {
		this.isEnCash = isEnCash;
	}

	@Column(name = "LeaveQty")
	public Integer getLeaveQty() {
		return this.leaveQty;
	}

	public void setLeaveQty(Integer leaveQty) {
		this.leaveQty = leaveQty;
	}

	@Column(name = "ModifiedBy", length = 45)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedDate", nullable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
