package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SettingPfobs generated by hbm2java
 */
@Entity
@Table(name = "setting_pfobs", catalog = "db_payroll")
public class SettingPfobs implements java.io.Serializable {

	private Integer pfobid;
	private Date timeStamp;
	private Double basicSalary;
	private Integer onOffStatus;
	private Long insertedBy;
	private Date insertTs;
	private Integer plantId;

	public SettingPfobs() {
	}

	public SettingPfobs(Double basicSalary, Integer onOffStatus,
			Long insertedBy, Date insertTs, Integer plantId) {
		this.basicSalary = basicSalary;
		this.onOffStatus = onOffStatus;
		this.insertedBy = insertedBy;
		this.insertTs = insertTs;
		this.plantId = plantId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PFOBId", unique = true, nullable = false)
	public Integer getPfobid() {
		return this.pfobid;
	}

	public void setPfobid(Integer pfobid) {
		this.pfobid = pfobid;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "BasicSalary", precision = 9)
	public Double getBasicSalary() {
		return this.basicSalary;
	}

	public void setBasicSalary(Double basicSalary) {
		this.basicSalary = basicSalary;
	}

	@Column(name = "On_Off_Status")
	public Integer getOnOffStatus() {
		return this.onOffStatus;
	}

	public void setOnOffStatus(Integer onOffStatus) {
		this.onOffStatus = onOffStatus;
	}

	@Column(name = "InsertedBy")
	public Long getInsertedBy() {
		return this.insertedBy;
	}

	public void setInsertedBy(Long insertedBy) {
		this.insertedBy = insertedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsertTs", length = 19)
	public Date getInsertTs() {
		return this.insertTs;
	}

	public void setInsertTs(Date insertTs) {
		this.insertTs = insertTs;
	}

	@Column(name = "PlantId")
	public Integer getPlantId() {
		return this.plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
	}

}
