package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SettingYearlybonus generated by hbm2java
 */
@Entity
@Table(name = "setting_yearlybonus", catalog = "db_payroll")
public class SettingYearlybonus implements java.io.Serializable {

	private Integer ybid;
	private Date timeStamp;
	private Double percentage;
	private Integer onOffStatus;
	private Long insertedBy;
	private Date insertTs;

	public SettingYearlybonus() {
	}

	public SettingYearlybonus(Double percentage, Integer onOffStatus,
			Long insertedBy, Date insertTs) {
		this.percentage = percentage;
		this.onOffStatus = onOffStatus;
		this.insertedBy = insertedBy;
		this.insertTs = insertTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "YBId", unique = true, nullable = false)
	public Integer getYbid() {
		return this.ybid;
	}

	public void setYbid(Integer ybid) {
		this.ybid = ybid;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "Percentage", precision = 9)
	public Double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Double percentage) {
		this.percentage = percentage;
	}

	@Column(name = "OnOffStatus")
	public Integer getOnOffStatus() {
		return this.onOffStatus;
	}

	public void setOnOffStatus(Integer onOffStatus) {
		this.onOffStatus = onOffStatus;
	}

	@Column(name = "InsertedBy")
	public Long getInsertedBy() {
		return this.insertedBy;
	}

	public void setInsertedBy(Long insertedBy) {
		this.insertedBy = insertedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsertTs", length = 19)
	public Date getInsertTs() {
		return this.insertTs;
	}

	public void setInsertTs(Date insertTs) {
		this.insertTs = insertTs;
	}

}
