package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SettingLateWarning generated by hbm2java
 */
@Entity
@Table(name = "setting_late_warning", catalog = "db_payroll")
public class SettingLateWarning implements java.io.Serializable {

	private Integer lwid;
	private Date timeStamp;
	private Integer lwonOff;

	public SettingLateWarning() {
	}

	public SettingLateWarning(Integer lwonOff) {
		this.lwonOff = lwonOff;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LWId", unique = true, nullable = false)
	public Integer getLwid() {
		return this.lwid;
	}

	public void setLwid(Integer lwid) {
		this.lwid = lwid;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "LWOnOff")
	public Integer getLwonOff() {
		return this.lwonOff;
	}

	public void setLwonOff(Integer lwonOff) {
		this.lwonOff = lwonOff;
	}

}
