package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SettingAbbreviation generated by hbm2java
 */
@Entity
@Table(name = "setting_abbreviation", catalog = "db_payroll")
public class SettingAbbreviation implements java.io.Serializable {

	private Integer abbrivationId;
	private String abbreviation;
	private String description;

	public SettingAbbreviation() {
	}

	public SettingAbbreviation(String abbreviation, String description) {
		this.abbreviation = abbreviation;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AbbrivationId", unique = true, nullable = false)
	public Integer getAbbrivationId() {
		return this.abbrivationId;
	}

	public void setAbbrivationId(Integer abbrivationId) {
		this.abbrivationId = abbrivationId;
	}

	@Column(name = "Abbreviation", nullable = false, length = 10)
	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	@Column(name = "Description", nullable = false, length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
