package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * SettingWeekoff generated by hbm2java
 */
@Entity
@Table(name = "setting_weekoff", catalog = "db_payroll", uniqueConstraints = @UniqueConstraint(columnNames = "WeekOffDay"))
public class SettingWeekoff implements java.io.Serializable {

	private Integer id;
	private Date timeStamp;
	private String weekOffDay;
	private Integer status;
	private Integer statusMonth;
	private Long insertedBy;
	private Date insertTs;
	private Long modifiedBy;
	private Date modifiedTs;
	private Integer plantId;

	public SettingWeekoff() {
	}

	public SettingWeekoff(String weekOffDay, Integer status,
			Integer statusMonth, Long insertedBy, Date insertTs,
			Long modifiedBy, Date modifiedTs, Integer plantId) {
		this.weekOffDay = weekOffDay;
		this.status = status;
		this.statusMonth = statusMonth;
		this.insertedBy = insertedBy;
		this.insertTs = insertTs;
		this.modifiedBy = modifiedBy;
		this.modifiedTs = modifiedTs;
		this.plantId = plantId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "WeekOffDay", unique = true, length = 15)
	public String getWeekOffDay() {
		return this.weekOffDay;
	}

	public void setWeekOffDay(String weekOffDay) {
		this.weekOffDay = weekOffDay;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "StatusMonth")
	public Integer getStatusMonth() {
		return this.statusMonth;
	}

	public void setStatusMonth(Integer statusMonth) {
		this.statusMonth = statusMonth;
	}

	@Column(name = "InsertedBy")
	public Long getInsertedBy() {
		return this.insertedBy;
	}

	public void setInsertedBy(Long insertedBy) {
		this.insertedBy = insertedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsertTs", length = 19)
	public Date getInsertTs() {
		return this.insertTs;
	}

	public void setInsertTs(Date insertTs) {
		this.insertTs = insertTs;
	}

	@Column(name = "ModifiedBy")
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedTs", length = 19)
	public Date getModifiedTs() {
		return this.modifiedTs;
	}

	public void setModifiedTs(Date modifiedTs) {
		this.modifiedTs = modifiedTs;
	}

	@Column(name = "PlantId")
	public Integer getPlantId() {
		return this.plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
	}

}
