package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SettingProfTax generated by hbm2java
 */
@Entity
@Table(name = "setting_prof_tax", catalog = "db_payroll")
public class SettingProfTax implements java.io.Serializable {

	private Integer ptid;
	private Date timeStamp;
	private Double salaryFrom1;
	private Double salaryTo1;
	private Double yearlyAmount1;
	private String exceptionMonth1;
	private Double exceptionAmount1;
	private Double salaryFrom2;
	private Double yearlyAmount2;
	private String exceptionMonth2;
	private Double exceptionAmount2;
	private Long insertedBy;
	private Date insertTs;
	private Long modifiedBy;
	private Date modifiedTs;
	private Integer plantId;

	public SettingProfTax() {
	}

	public SettingProfTax(Double salaryFrom1, Double salaryTo1,
			Double yearlyAmount1, String exceptionMonth1,
			Double exceptionAmount1, Double salaryFrom2, Double yearlyAmount2,
			String exceptionMonth2, Double exceptionAmount2, Long insertedBy,
			Date insertTs, Long modifiedBy, Date modifiedTs, Integer plantId) {
		this.salaryFrom1 = salaryFrom1;
		this.salaryTo1 = salaryTo1;
		this.yearlyAmount1 = yearlyAmount1;
		this.exceptionMonth1 = exceptionMonth1;
		this.exceptionAmount1 = exceptionAmount1;
		this.salaryFrom2 = salaryFrom2;
		this.yearlyAmount2 = yearlyAmount2;
		this.exceptionMonth2 = exceptionMonth2;
		this.exceptionAmount2 = exceptionAmount2;
		this.insertedBy = insertedBy;
		this.insertTs = insertTs;
		this.modifiedBy = modifiedBy;
		this.modifiedTs = modifiedTs;
		this.plantId = plantId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PTId", unique = true, nullable = false)
	public Integer getPtid() {
		return this.ptid;
	}

	public void setPtid(Integer ptid) {
		this.ptid = ptid;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "SalaryFrom1", precision = 9)
	public Double getSalaryFrom1() {
		return this.salaryFrom1;
	}

	public void setSalaryFrom1(Double salaryFrom1) {
		this.salaryFrom1 = salaryFrom1;
	}

	@Column(name = "SalaryTo1", precision = 9)
	public Double getSalaryTo1() {
		return this.salaryTo1;
	}

	public void setSalaryTo1(Double salaryTo1) {
		this.salaryTo1 = salaryTo1;
	}

	@Column(name = "YearlyAmount1", precision = 9)
	public Double getYearlyAmount1() {
		return this.yearlyAmount1;
	}

	public void setYearlyAmount1(Double yearlyAmount1) {
		this.yearlyAmount1 = yearlyAmount1;
	}

	@Column(name = "ExceptionMonth1", length = 45)
	public String getExceptionMonth1() {
		return this.exceptionMonth1;
	}

	public void setExceptionMonth1(String exceptionMonth1) {
		this.exceptionMonth1 = exceptionMonth1;
	}

	@Column(name = "ExceptionAmount1", precision = 9)
	public Double getExceptionAmount1() {
		return this.exceptionAmount1;
	}

	public void setExceptionAmount1(Double exceptionAmount1) {
		this.exceptionAmount1 = exceptionAmount1;
	}

	@Column(name = "SalaryFrom2", precision = 9)
	public Double getSalaryFrom2() {
		return this.salaryFrom2;
	}

	public void setSalaryFrom2(Double salaryFrom2) {
		this.salaryFrom2 = salaryFrom2;
	}

	@Column(name = "YearlyAmount2", precision = 9)
	public Double getYearlyAmount2() {
		return this.yearlyAmount2;
	}

	public void setYearlyAmount2(Double yearlyAmount2) {
		this.yearlyAmount2 = yearlyAmount2;
	}

	@Column(name = "ExceptionMonth2", length = 45)
	public String getExceptionMonth2() {
		return this.exceptionMonth2;
	}

	public void setExceptionMonth2(String exceptionMonth2) {
		this.exceptionMonth2 = exceptionMonth2;
	}

	@Column(name = "ExceptionAmount2", precision = 9)
	public Double getExceptionAmount2() {
		return this.exceptionAmount2;
	}

	public void setExceptionAmount2(Double exceptionAmount2) {
		this.exceptionAmount2 = exceptionAmount2;
	}

	@Column(name = "InsertedBy")
	public Long getInsertedBy() {
		return this.insertedBy;
	}

	public void setInsertedBy(Long insertedBy) {
		this.insertedBy = insertedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsertTs", length = 19)
	public Date getInsertTs() {
		return this.insertTs;
	}

	public void setInsertTs(Date insertTs) {
		this.insertTs = insertTs;
	}

	@Column(name = "ModifiedBy")
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedTs", length = 19)
	public Date getModifiedTs() {
		return this.modifiedTs;
	}

	public void setModifiedTs(Date modifiedTs) {
		this.modifiedTs = modifiedTs;
	}

	@Column(name = "PlantId")
	public Integer getPlantId() {
		return this.plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
	}

}
