package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SettingLwf generated by hbm2java
 */
@Entity
@Table(name = "setting_lwf", catalog = "db_payroll")
public class SettingLwf implements java.io.Serializable {

	private Integer lwfid;
	private Date timeStamp;
	private Integer monthFirst;
	private Integer monthSecond;
	private Double lwfamount;
	private Long insertedBy;
	private Date insertTs;
	private Long modifiedBy;
	private Date modifiedTs;
	private Integer plantId;

	public SettingLwf() {
	}

	public SettingLwf(Integer monthFirst, Integer monthSecond,
			Double lwfamount, Long insertedBy, Date insertTs, Long modifiedBy,
			Date modifiedTs, Integer plantId) {
		this.monthFirst = monthFirst;
		this.monthSecond = monthSecond;
		this.lwfamount = lwfamount;
		this.insertedBy = insertedBy;
		this.insertTs = insertTs;
		this.modifiedBy = modifiedBy;
		this.modifiedTs = modifiedTs;
		this.plantId = plantId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LWFId", unique = true, nullable = false)
	public Integer getLwfid() {
		return this.lwfid;
	}

	public void setLwfid(Integer lwfid) {
		this.lwfid = lwfid;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "MonthFirst")
	public Integer getMonthFirst() {
		return this.monthFirst;
	}

	public void setMonthFirst(Integer monthFirst) {
		this.monthFirst = monthFirst;
	}

	@Column(name = "MonthSecond")
	public Integer getMonthSecond() {
		return this.monthSecond;
	}

	public void setMonthSecond(Integer monthSecond) {
		this.monthSecond = monthSecond;
	}

	@Column(name = "LWFAmount", precision = 9)
	public Double getLwfamount() {
		return this.lwfamount;
	}

	public void setLwfamount(Double lwfamount) {
		this.lwfamount = lwfamount;
	}

	@Column(name = "InsertedBy")
	public Long getInsertedBy() {
		return this.insertedBy;
	}

	public void setInsertedBy(Long insertedBy) {
		this.insertedBy = insertedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsertTs", length = 19)
	public Date getInsertTs() {
		return this.insertTs;
	}

	public void setInsertTs(Date insertTs) {
		this.insertTs = insertTs;
	}

	@Column(name = "ModifiedBy")
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedTs", length = 19)
	public Date getModifiedTs() {
		return this.modifiedTs;
	}

	public void setModifiedTs(Date modifiedTs) {
		this.modifiedTs = modifiedTs;
	}

	@Column(name = "PlantId")
	public Integer getPlantId() {
		return this.plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
	}

}
