package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ShiftAllocation generated by hbm2java
 */
@Entity
@Table(name = "shift_allocation", catalog = "db_payroll", uniqueConstraints = @UniqueConstraint(columnNames = "EmpId"))
public class ShiftAllocation implements java.io.Serializable {

	private Long shiftAlloId;
	private SettingShiftType settingShiftType;
	private long empId;
	private long departmentId;
	private Integer plantId;

	public ShiftAllocation() {
	}

	public ShiftAllocation(long empId, long departmentId) {
		this.empId = empId;
		this.departmentId = departmentId;
	}

	public ShiftAllocation(SettingShiftType settingShiftType, long empId,
			long departmentId, Integer plantId) {
		this.settingShiftType = settingShiftType;
		this.empId = empId;
		this.departmentId = departmentId;
		this.plantId = plantId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ShiftAlloId", unique = true, nullable = false)
	public Long getShiftAlloId() {
		return this.shiftAlloId;
	}

	public void setShiftAlloId(Long shiftAlloId) {
		this.shiftAlloId = shiftAlloId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ShiftId")
	public SettingShiftType getSettingShiftType() {
		return this.settingShiftType;
	}

	public void setSettingShiftType(SettingShiftType settingShiftType) {
		this.settingShiftType = settingShiftType;
	}

	@Column(name = "EmpId", unique = true, nullable = false)
	public long getEmpId() {
		return this.empId;
	}

	public void setEmpId(long empId) {
		this.empId = empId;
	}

	@Column(name = "DepartmentId", nullable = false)
	public long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(long departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "PlantId")
	public Integer getPlantId() {
		return this.plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
	}

}
