package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * StaffLateCount generated by hbm2java
 */
@Entity
@Table(name = "staff_late_count", catalog = "db_payroll", uniqueConstraints = @UniqueConstraint(columnNames = {
		"EmpId", "Month", "Year" }))
public class StaffLateCount implements java.io.Serializable {

	private Long slcountId;
	private Date timeStamp;
	private Long empId;
	private Integer month;
	private Integer year;
	private Integer count;

	public StaffLateCount() {
	}

	public StaffLateCount(Long empId, Integer month, Integer year, Integer count) {
		this.empId = empId;
		this.month = month;
		this.year = year;
		this.count = count;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SLCountId", unique = true, nullable = false)
	public Long getSlcountId() {
		return this.slcountId;
	}

	public void setSlcountId(Long slcountId) {
		this.slcountId = slcountId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "EmpId")
	public Long getEmpId() {
		return this.empId;
	}

	public void setEmpId(Long empId) {
		this.empId = empId;
	}

	@Column(name = "Month")
	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	@Column(name = "Year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "Count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

}
