package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SvMeetingAttendees generated by hbm2java
 */
@Entity
@Table(name = "sv_meeting_attendees", catalog = "db_payroll")
public class SvMeetingAttendees implements java.io.Serializable {

	private Integer attendeeId;
	private SvMeetingMaster svMeetingMaster;
	private Integer empId;

	public SvMeetingAttendees() {
	}

	public SvMeetingAttendees(SvMeetingMaster svMeetingMaster, Integer empId) {
		this.svMeetingMaster = svMeetingMaster;
		this.empId = empId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AttendeeId", unique = true, nullable = false)
	public Integer getAttendeeId() {
		return this.attendeeId;
	}

	public void setAttendeeId(Integer attendeeId) {
		this.attendeeId = attendeeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MeetingId")
	public SvMeetingMaster getSvMeetingMaster() {
		return this.svMeetingMaster;
	}

	public void setSvMeetingMaster(SvMeetingMaster svMeetingMaster) {
		this.svMeetingMaster = svMeetingMaster;
	}

	@Column(name = "EmpId")
	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

}
