package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SvProjectMaster generated by hbm2java
 */
@Entity
@Table(name = "sv_project_master", catalog = "db_payroll")
public class SvProjectMaster implements java.io.Serializable {

	private Integer projectId;
	private SvClientMaster svClientMaster;
	private String projectCode;
	private String projectName;
	private String projectDesc;
	private Date startDate;
	private Date endDate;
	private String projectScope;
	private String projectStandard;
	private String projectStatus;
	private String projecttype;
	private Integer createdBy;
	private Date createdOn;
	private Integer updatedBy;
	private Date updatedOn;
	private Integer deletedBy;
	private Date deletedOn;
	private Byte isDeleted;
	private Set svProjectLevels = new HashSet(0);

	public SvProjectMaster() {
	}

	public SvProjectMaster(SvClientMaster svClientMaster, String projectCode,
			String projectName, String projectDesc, Date startDate,
			Date endDate, String projectScope, String projectStandard,
			String projectStatus, String projecttype, Integer createdBy,
			Date createdOn, Integer updatedBy, Date updatedOn,
			Integer deletedBy, Date deletedOn, Byte isDeleted,
			Set svProjectLevels) {
		this.svClientMaster = svClientMaster;
		this.projectCode = projectCode;
		this.projectName = projectName;
		this.projectDesc = projectDesc;
		this.startDate = startDate;
		this.endDate = endDate;
		this.projectScope = projectScope;
		this.projectStandard = projectStandard;
		this.projectStatus = projectStatus;
		this.projecttype = projecttype;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.deletedBy = deletedBy;
		this.deletedOn = deletedOn;
		this.isDeleted = isDeleted;
		this.svProjectLevels = svProjectLevels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "projectId", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ClientId")
	public SvClientMaster getSvClientMaster() {
		return this.svClientMaster;
	}

	public void setSvClientMaster(SvClientMaster svClientMaster) {
		this.svClientMaster = svClientMaster;
	}

	@Column(name = "projectCode")
	public String getProjectCode() {
		return this.projectCode;
	}

	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	@Column(name = "projectName")
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "projectDesc")
	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startDate", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endDate", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "projectScope")
	public String getProjectScope() {
		return this.projectScope;
	}

	public void setProjectScope(String projectScope) {
		this.projectScope = projectScope;
	}

	@Column(name = "projectStandard")
	public String getProjectStandard() {
		return this.projectStandard;
	}

	public void setProjectStandard(String projectStandard) {
		this.projectStandard = projectStandard;
	}

	@Column(name = "projectStatus", length = 9)
	public String getProjectStatus() {
		return this.projectStatus;
	}

	public void setProjectStatus(String projectStatus) {
		this.projectStatus = projectStatus;
	}

	@Column(name = "projecttype", length = 45)
	public String getProjecttype() {
		return this.projecttype;
	}

	public void setProjecttype(String projecttype) {
		this.projecttype = projecttype;
	}

	@Column(name = "CreatedBy")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "UpdatedBy")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedOn", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "DeletedBy")
	public Integer getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(Integer deletedBy) {
		this.deletedBy = deletedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeletedOn", length = 19)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@Column(name = "IsDeleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "svProjectMaster")
	public Set getSvProjectLevels() {
		return this.svProjectLevels;
	}

	public void setSvProjectLevels(Set svProjectLevels) {
		this.svProjectLevels = svProjectLevels;
	}

}
