package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SvProjectAttachment generated by hbm2java
 */
@Entity
@Table(name = "sv_project_attachment", catalog = "db_payroll")
public class SvProjectAttachment implements java.io.Serializable {

	private Integer projectAttId;
	private String fileName;
	private String orgFileName;
	private Integer projectId;

	public SvProjectAttachment() {
	}

	public SvProjectAttachment(String fileName, String orgFileName,
			Integer projectId) {
		this.fileName = fileName;
		this.orgFileName = orgFileName;
		this.projectId = projectId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "projectAttId", unique = true, nullable = false)
	public Integer getProjectAttId() {
		return this.projectAttId;
	}

	public void setProjectAttId(Integer projectAttId) {
		this.projectAttId = projectAttId;
	}

	@Column(name = "fileName")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "orgFileName")
	public String getOrgFileName() {
		return this.orgFileName;
	}

	public void setOrgFileName(String orgFileName) {
		this.orgFileName = orgFileName;
	}

	@Column(name = "projectId")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

}
