package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SvProjectTeamMember generated by hbm2java
 */
@Entity
@Table(name = "sv_project_team_member", catalog = "db_payroll")
public class SvProjectTeamMember implements java.io.Serializable {

	private Integer projectTeamId;
	private Integer empId;
	private Integer projectId;

	public SvProjectTeamMember() {
	}

	public SvProjectTeamMember(Integer empId, Integer projectId) {
		this.empId = empId;
		this.projectId = projectId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "projectTeamId", unique = true, nullable = false)
	public Integer getProjectTeamId() {
		return this.projectTeamId;
	}

	public void setProjectTeamId(Integer projectTeamId) {
		this.projectTeamId = projectTeamId;
	}

	@Column(name = "empId")
	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	@Column(name = "projectId")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

}
