package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SvTaskMaster generated by hbm2java
 */
@Entity
@Table(name = "sv_task_master", catalog = "db_payroll")
public class SvTaskMaster implements java.io.Serializable {

	private Integer taskId;
	private String parentType;
	private Integer parentTypeId;
	private Integer parentTaskId;
	private String taskName;
	private String taskDescrip;
	private Integer assignToEmp;
	private Date startDateTime;
	private Date endDateTime;
	private String estimatedHr;
	private String status;
	private Integer createdBy;
	private Date createdon;
	private Integer updateBy;
	private Date updateOn;
	private String deletedBy;
	private Date deletedOn;
	private Boolean isDeleted;
	private Set svQueryLogs = new HashSet(0);
	private Set svTaskAssignemps = new HashSet(0);

	public SvTaskMaster() {
	}

	public SvTaskMaster(String parentType, Integer parentTypeId,
			Integer parentTaskId, String taskName, String taskDescrip,
			Integer assignToEmp, Date startDateTime, Date endDateTime,
			String estimatedHr, String status, Integer createdBy,
			Date createdon, Integer updateBy, Date updateOn, String deletedBy,
			Date deletedOn, Boolean isDeleted, Set svQueryLogs,
			Set svTaskAssignemps) {
		this.parentType = parentType;
		this.parentTypeId = parentTypeId;
		this.parentTaskId = parentTaskId;
		this.taskName = taskName;
		this.taskDescrip = taskDescrip;
		this.assignToEmp = assignToEmp;
		this.startDateTime = startDateTime;
		this.endDateTime = endDateTime;
		this.estimatedHr = estimatedHr;
		this.status = status;
		this.createdBy = createdBy;
		this.createdon = createdon;
		this.updateBy = updateBy;
		this.updateOn = updateOn;
		this.deletedBy = deletedBy;
		this.deletedOn = deletedOn;
		this.isDeleted = isDeleted;
		this.svQueryLogs = svQueryLogs;
		this.svTaskAssignemps = svTaskAssignemps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TaskId", unique = true, nullable = false)
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@Column(name = "ParentType", length = 45)
	public String getParentType() {
		return this.parentType;
	}

	public void setParentType(String parentType) {
		this.parentType = parentType;
	}

	@Column(name = "ParentTypeId")
	public Integer getParentTypeId() {
		return this.parentTypeId;
	}

	public void setParentTypeId(Integer parentTypeId) {
		this.parentTypeId = parentTypeId;
	}

	@Column(name = "ParentTaskId")
	public Integer getParentTaskId() {
		return this.parentTaskId;
	}

	public void setParentTaskId(Integer parentTaskId) {
		this.parentTaskId = parentTaskId;
	}

	@Column(name = "TaskName", length = 500)
	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "TaskDescrip", length = 500)
	public String getTaskDescrip() {
		return this.taskDescrip;
	}

	public void setTaskDescrip(String taskDescrip) {
		this.taskDescrip = taskDescrip;
	}

	@Column(name = "AssignToEmp")
	public Integer getAssignToEmp() {
		return this.assignToEmp;
	}

	public void setAssignToEmp(Integer assignToEmp) {
		this.assignToEmp = assignToEmp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDateTime", length = 19)
	public Date getStartDateTime() {
		return this.startDateTime;
	}

	public void setStartDateTime(Date startDateTime) {
		this.startDateTime = startDateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDateTime", length = 19)
	public Date getEndDateTime() {
		return this.endDateTime;
	}

	public void setEndDateTime(Date endDateTime) {
		this.endDateTime = endDateTime;
	}

	@Column(name = "EstimatedHr", length = 45)
	public String getEstimatedHr() {
		return this.estimatedHr;
	}

	public void setEstimatedHr(String estimatedHr) {
		this.estimatedHr = estimatedHr;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CreatedBy")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Createdon", length = 19)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "UpdateBy")
	public Integer getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdateOn", length = 19)
	public Date getUpdateOn() {
		return this.updateOn;
	}

	public void setUpdateOn(Date updateOn) {
		this.updateOn = updateOn;
	}

	@Column(name = "DeletedBy", length = 45)
	public String getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(String deletedBy) {
		this.deletedBy = deletedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeletedOn", length = 19)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "svTaskMaster")
	public Set getSvQueryLogs() {
		return this.svQueryLogs;
	}

	public void setSvQueryLogs(Set svQueryLogs) {
		this.svQueryLogs = svQueryLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "svTaskMaster")
	public Set getSvTaskAssignemps() {
		return this.svTaskAssignemps;
	}

	public void setSvTaskAssignemps(Set svTaskAssignemps) {
		this.svTaskAssignemps = svTaskAssignemps;
	}

}
