package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SvWorksheet generated by hbm2java
 */
@Entity
@Table(name = "sv_worksheet", catalog = "db_payroll")
public class SvWorksheet implements java.io.Serializable {

	private Integer workSheetId;
	private Integer taskId;
	private Double bh;
	private Double oh;
	private Double ms;
	private Double training;
	private Double shiftHrs;

	public SvWorksheet() {
	}

	public SvWorksheet(Integer taskId, Double bh, Double oh, Double ms,
			Double training, Double shiftHrs) {
		this.taskId = taskId;
		this.bh = bh;
		this.oh = oh;
		this.ms = ms;
		this.training = training;
		this.shiftHrs = shiftHrs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "WorkSheetId", unique = true, nullable = false)
	public Integer getWorkSheetId() {
		return this.workSheetId;
	}

	public void setWorkSheetId(Integer workSheetId) {
		this.workSheetId = workSheetId;
	}

	@Column(name = "TaskId")
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@Column(name = "BH", precision = 5)
	public Double getBh() {
		return this.bh;
	}

	public void setBh(Double bh) {
		this.bh = bh;
	}

	@Column(name = "OH", precision = 5)
	public Double getOh() {
		return this.oh;
	}

	public void setOh(Double oh) {
		this.oh = oh;
	}

	@Column(name = "MS", precision = 5)
	public Double getMs() {
		return this.ms;
	}

	public void setMs(Double ms) {
		this.ms = ms;
	}

	@Column(name = "Training", precision = 5)
	public Double getTraining() {
		return this.training;
	}

	public void setTraining(Double training) {
		this.training = training;
	}

	@Column(name = "ShiftHrs", precision = 5)
	public Double getShiftHrs() {
		return this.shiftHrs;
	}

	public void setShiftHrs(Double shiftHrs) {
		this.shiftHrs = shiftHrs;
	}

}
