package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * UserActionRel generated by hbm2java
 */
@Entity
@Table(name = "user_action_rel", catalog = "db_payroll")
public class UserActionRel implements java.io.Serializable {

	private int userActionRelId;
	private Date timeStamp;
	private Integer idOfUser;
	private Integer actionId;
	private Byte isDeleted;
	private Integer userId;

	public UserActionRel() {
	}

	public UserActionRel(int userActionRelId) {
		this.userActionRelId = userActionRelId;
	}

	public UserActionRel(int userActionRelId, Integer idOfUser,
			Integer actionId, Byte isDeleted, Integer userId) {
		this.userActionRelId = userActionRelId;
		this.idOfUser = idOfUser;
		this.actionId = actionId;
		this.isDeleted = isDeleted;
		this.userId = userId;
	}

	@Id
	@Column(name = "UserActionRelId", unique = true, nullable = false)
	public int getUserActionRelId() {
		return this.userActionRelId;
	}

	public void setUserActionRelId(int userActionRelId) {
		this.userActionRelId = userActionRelId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "IdOfUser")
	public Integer getIdOfUser() {
		return this.idOfUser;
	}

	public void setIdOfUser(Integer idOfUser) {
		this.idOfUser = idOfUser;
	}

	@Column(name = "ActionId")
	public Integer getActionId() {
		return this.actionId;
	}

	public void setActionId(Integer actionId) {
		this.actionId = actionId;
	}

	@Column(name = "IsDeleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "UserId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
