package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UtilDepartment generated by hbm2java
 */
@Entity
@Table(name = "util_department", catalog = "db_payroll")
public class UtilDepartment implements java.io.Serializable {

	private Long departmentId;
	private String department;
	private Long modifiedBy;
	private Date modifiedDate;
	private Set employeeMasters = new HashSet(0);

	public UtilDepartment() {
	}

	public UtilDepartment(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public UtilDepartment(String department, Long modifiedBy,
			Date modifiedDate, Set employeeMasters) {
		this.department = department;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.employeeMasters = employeeMasters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DepartmentId", unique = true, nullable = false)
	public Long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "Department", length = 45)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "ModifiedBy")
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedDate", nullable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilDepartment")
	public Set getEmployeeMasters() {
		return this.employeeMasters;
	}

	public void setEmployeeMasters(Set employeeMasters) {
		this.employeeMasters = employeeMasters;
	}

}
