package com.custinfo.model;

// Generated 30 Aug, 2016 5:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UtilDesignation generated by hbm2java
 */
@Entity
@Table(name = "util_designation", catalog = "db_payroll", uniqueConstraints = @UniqueConstraint(columnNames = "Designation"))
public class UtilDesignation implements java.io.Serializable {

	private long designationId;
	private String designation;
	private Long modifiedBy;
	private Date modifiedDate;
	private Set employeeMasters = new HashSet(0);

	public UtilDesignation() {
	}

	public UtilDesignation(long designationId, String designation,
			Date modifiedDate) {
		this.designationId = designationId;
		this.designation = designation;
		this.modifiedDate = modifiedDate;
	}

	public UtilDesignation(long designationId, String designation,
			Long modifiedBy, Date modifiedDate, Set employeeMasters) {
		this.designationId = designationId;
		this.designation = designation;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.employeeMasters = employeeMasters;
	}

	@Id
	@Column(name = "DesignationId", unique = true, nullable = false)
	public long getDesignationId() {
		return this.designationId;
	}

	public void setDesignationId(long designationId) {
		this.designationId = designationId;
	}

	@Column(name = "Designation", unique = true, nullable = false, length = 45)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "ModifiedBy")
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedDate", nullable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilDesignation")
	public Set getEmployeeMasters() {
		return this.employeeMasters;
	}

	public void setEmployeeMasters(Set employeeMasters) {
		this.employeeMasters = employeeMasters;
	}

}
